import { beforeEach, describe, expect, it, vi } from "vitest";
import type { EventEntity } from "@paddle/paddle-node-sdk";
const m = vi.hoisted(() => ({ owner: vi.fn(), environment: vi.fn(), addon: vi.fn(), upsert: vi.fn(), business: vi.fn(), ledger: vi.fn(), record: vi.fn(), suspend: vi.fn(), lock: vi.fn(), cancel: vi.fn(), update: vi.fn(), price: vi.fn(), create: vi.fn(), get: vi.fn(), payment: vi.fn() }));
vi.mock("@/server/websites/service", () => ({ requireWebsiteManager: m.owner }));
vi.mock("@/server/lib/paddle", () => ({ getPaddleEnvironment: m.environment, getPaddleServerClient: () => ({ subscriptions: { cancel: m.cancel, update: m.update, getPaymentMethodChangeTransaction: m.payment }, prices: { get: m.price }, transactions: { create: m.create, get: m.get } }) }));
vi.mock("@/server/db/prisma", () => {
 const tx = { $queryRaw: m.lock, websiteAddon: { findUnique: m.addon, findUniqueOrThrow: m.addon, upsert: m.upsert }, business: { findUnique: m.business }, websiteBillingEvent: { findUnique: m.ledger, create: m.record }, businessWebsite: { updateMany: m.suspend } };
 return { prisma: { ...tx, $transaction: (work: (tx: unknown) => unknown) => work(tx) } };
});
import { startWebsiteCheckout, changeWebsiteBilling, recoverWebsitePayment, syncWebsiteAddon } from "@/server/websites/billing";
function event(status = "active", date = "2026-09-30T12:00:00Z", overrides = {}) {
 return { eventId: "evt_test", eventType: "subscription.updated", occurredAt: date, data: { id: "sub_website", customerId: "ctm_test", status, currentBillingPeriod: { endsAt: "2026-10-30T12:00:00Z" }, items: [{ price: { id: "pri_website" } }], customData: { puragenda_addon: "website", puragenda_business_id: "business-a" }, ...overrides } } as unknown as EventEntity;
}
describe("website addon billing safety", () => {
 beforeEach(() => { vi.resetAllMocks(); vi.stubEnv("PADDLE_API_KEY", "test_sdbx_local_mock_only"); vi.stubEnv("WEBSITE_PRICE_STANDARD", "pri_website"); m.environment.mockReturnValue("sandbox"); m.owner.mockResolvedValue({business:{id:"business-a"}}); m.business.mockResolvedValue({id:"business-a"}); m.addon.mockResolvedValue({checkoutTransactionId:"txn_authorized"}); m.get.mockResolvedValue({subscriptionId:"sub_website"}); m.ledger.mockResolvedValue(null); m.price.mockResolvedValue({id:"pri_website",status:"active",billingCycle:{interval:"month",frequency:1},unitPrice:{amount:"9990",currencyCode:"CLP"}}); });
 it("pins only the website subscription and serializes first delivery", async () => { expect(await syncWebsiteAddon(event())).toBe(true);expect(m.lock).toHaveBeenCalled();expect(m.upsert).toHaveBeenCalledWith(expect.objectContaining({where:{businessId:"business-a"},update:expect.objectContaining({paddleSubscriptionId:"sub_website",status:"ACTIVE"})}));expect(m.record).toHaveBeenCalledWith({data:{eventId:"evt_test"}}); });
 it("does not trust client custom data or let addon transactions reach base billing", async () => {m.addon.mockResolvedValue(null);await expect(syncWebsiteAddon(event())).rejects.toThrow("checkout autorizado");expect(m.upsert).not.toHaveBeenCalled();expect(await syncWebsiteAddon({...event(),eventType:"transaction.completed"} as unknown as EventEntity)).toBe(true);});
 it("checks the created event transaction and rejects another checkout", async () => {await expect(syncWebsiteAddon(event("active",undefined,{transactionId:"txn_other"}))).rejects.toThrow("no corresponde");expect(m.upsert).not.toHaveBeenCalled();});
 it("deduplicates and rejects older deliveries", async () => { m.ledger.mockResolvedValue({eventId:"evt_test"});await syncWebsiteAddon(event());expect(m.upsert).not.toHaveBeenCalled();m.ledger.mockResolvedValue(null);m.addon.mockResolvedValue({lastEventAt:new Date("2026-10-01")});await syncWebsiteAddon(event());expect(m.upsert).not.toHaveBeenCalled(); });
 it("rejects swapping an active provider subscription", async () => {m.addon.mockResolvedValue({paddleSubscriptionId:"sub_other",status:"ACTIVE"});await expect(syncWebsiteAddon(event())).rejects.toThrow("distinta");expect(m.upsert).not.toHaveBeenCalled();});
 it("suspends only website publication on missed payment", async () => {await syncWebsiteAddon(event("past_due"));expect(m.suspend).toHaveBeenCalledWith({where:{businessId:"business-a",status:"PUBLISHED"},data:{status:"SUSPENDED"}});});
 it("leaves unrelated subscriptions and live environments untouched", async () => {expect(await syncWebsiteAddon(event("active",undefined,{customData:{puragenda_business_id:"business-a"}}))).toBe(false);m.environment.mockReturnValue("production");await syncWebsiteAddon(event());expect(m.upsert).not.toHaveBeenCalled();await expect(startWebsiteCheckout()).rejects.toThrow("solo en sandbox");});
 it("requires owner authorization and explicit cancellation confirmation", async () => {await expect(changeWebsiteBilling("cancel",false)).rejects.toThrow("Confirma");expect(m.cancel).not.toHaveBeenCalled();m.addon.mockResolvedValue({provider:"paddle",paddleSubscriptionId:"sub_website"});await changeWebsiteBilling("cancel",true);expect(m.owner).toHaveBeenCalledWith(true);expect(m.cancel).toHaveBeenCalledWith("sub_website",{effectiveFrom:"next_billing_period"});});
 it("reactivates only scheduled cancellation and never grants entitlement optimistically", async () => {m.addon.mockResolvedValue({provider:"paddle",paddleSubscriptionId:"sub_website",status:"ACTIVE",cancelAt:new Date("2026-10-30")});await changeWebsiteBilling("reactivate",true);expect(m.update).toHaveBeenCalledWith("sub_website",{scheduledChange:null});expect(m.upsert).not.toHaveBeenCalled();m.addon.mockResolvedValue({provider:"paddle",paddleSubscriptionId:"sub_website",status:"CANCELLED"});await expect(changeWebsiteBilling("reactivate",true)).rejects.toThrow("nuevo checkout");});
 it("recovers payment only for the owner's existing addon", async () => {m.addon.mockResolvedValue({status:"PAST_DUE",provider:"paddle",paddleSubscriptionId:"sub_website"});m.payment.mockResolvedValue({id:"txn_recovery"});expect(await recoverWebsitePayment()).toEqual({transactionId:"txn_recovery"});expect(m.payment).toHaveBeenCalledWith("sub_website");expect(m.owner).toHaveBeenCalledWith(true);expect(m.upsert).not.toHaveBeenCalled();});
 it("reuses an unfinished checkout instead of creating duplicate subscriptions", async () => {m.addon.mockResolvedValue({status:"INACTIVE",checkoutTransactionId:"txn_pending"});m.get.mockResolvedValue({id:"txn_pending",status:"ready"});expect(await startWebsiteCheckout()).toEqual({transactionId:"txn_pending"});expect(m.create).not.toHaveBeenCalled();});
});

