import { beforeEach, describe, expect, it, vi } from "vitest";
import sharp from "sharp";
import type { Prisma } from "@prisma/client";
const m = vi.hoisted(() => ({ manager: vi.fn(), ensure: vi.fn(), find: vi.fn(), create: vi.fn(), update: vi.fn(), count: vi.fn(), query: vi.fn(), upload: vi.fn(), destroy: vi.fn() }));
vi.mock("@/server/websites/service", () => ({ requireWebsiteManager: m.manager, ensureWebsite: m.ensure }));
vi.mock("@/server/lib/cloudinary", () => ({ cloudinary: { uploader: { upload: m.upload, destroy: m.destroy } } }));
vi.mock("@/server/db/prisma", () => { const db = { websiteMedia: { findFirst: m.find, findMany: m.find, create: m.create, update: m.update, count: m.count }, $queryRaw: m.query }; return { prisma: { ...db, $transaction: (callback: (db: unknown) => unknown) => callback(db) } }; });
import { normalizeWebsiteImage, storeWebsiteImage, validateWebsiteAssets, deleteWebsiteAsset } from "@/server/websites/media";
import { emptyBellaConfig } from "@/websites/config";
import { POST } from "@/app/api/website/media/route";
const asset = { id: "asset-a", publicId: "puragenda_websites/tenant-a/photo", secureUrl: "https://res.cloudinary.com/qa/image/upload/photo.webp", width: 128, height: 128, format: "webp" as const, bytes: 200 };
async function photo(width = 128, height = 128) { const data = await sharp({ create: { width, height, channels: 3, background: "#ce7467" } }).png().withMetadata({ exif: { IFD0: { Artist: "private" } } }).toBuffer(); return new File([new Uint8Array(data)], "photo.png", { type: "image/png" }); }
beforeEach(() => { vi.resetAllMocks(); m.manager.mockResolvedValue({ business: { id: "tenant-a", slug: "tenant-a" } }); m.ensure.mockResolvedValue({ id: "website-a" }); m.count.mockResolvedValue(0); m.create.mockImplementation(async ({ data }) => ({ id: "asset-a", ...data })); m.upload.mockResolvedValue({ secure_url: asset.secureUrl }); m.destroy.mockResolvedValue({ result: "ok" }); });
describe("website media ownership and decoding", () => {
  it("rejects cross-origin upload requests before authentication or parsing", async () => { const response = await POST(new Request("http://localhost:3005/api/website/media", { method: "POST", headers: { Origin: "https://evil.test" }, body: "junk" })); expect(response.status).toBe(403); expect(m.manager).not.toHaveBeenCalled(); });
  it("caps multipart body size even when the browser does not declare Content-Length", async () => { const response = await POST(new Request("http://localhost:3005/api/website/media", { method: "POST", headers: { Origin: "http://localhost:3005" }, body: new Uint8Array(6 * 1024 * 1024 + 1) })); expect(response.status).toBe(413); expect(m.upload).not.toHaveBeenCalled(); });
  it("checks the transport Host, not a loopback alias or forwarded host", async () => { const allowed = await POST(new Request("http://127.0.0.1:3005/api/website/media", { method: "POST", headers: { Host: "localhost:3005", Origin: "http://localhost:3005" }, body: new Uint8Array(6 * 1024 * 1024 + 1) })); expect(allowed.status).toBe(413); const rejected = await POST(new Request("http://127.0.0.1:3005/api/website/media", { method: "POST", headers: { Host: "localhost:3005", Origin: "https://evil.test", "x-forwarded-host": "evil.test" }, body: "bad" })); expect(rejected.status).toBe(403); });
  it("rejects unauthenticated upload before decoding or provider operations", async () => { m.manager.mockRejectedValue(new Error("No autorizado")); await expect(storeWebsiteImage(new FormData())).rejects.toThrow("No autorizado"); expect(m.upload).not.toHaveBeenCalled(); });
  it("checks real MIME rather than trusting browser headers", async () => { const real = await photo(); const spoofed = new File([await real.arrayBuffer()], "photo.jpg", { type: "image/jpeg" }); await expect(normalizeWebsiteImage(spoofed, "hero")).rejects.toThrow("compatible"); await expect(normalizeWebsiteImage(new File(["<script>bad</script>"], "image.png", { type: "image/png" }), "hero")).rejects.toThrow("leer"); });
  it("rejects oversized uploads", async () => { await expect(normalizeWebsiteImage(new File([new Uint8Array(5 * 1024 * 1024 + 1)], "big.jpg", { type: "image/jpeg" }), "hero")).rejects.toThrow("5 MB"); });
  it("reduces large images by profile and strips EXIF metadata", async () => { const input = await photo(3000, 1500); const hero = await normalizeWebsiteImage(input, "hero"); const logo = await normalizeWebsiteImage(input, "logo"); const favicon = await normalizeWebsiteImage(input, "favicon"); expect(hero.info.width).toBe(2400); expect(logo.info.width).toBe(800); expect(favicon.info.width).toBe(256); const metadata = await sharp(hero.data).metadata(); expect(metadata.exif).toBeUndefined(); expect(metadata.format).toBe("webp"); });
  it("uses the existing authenticated Cloudinary SDK, chooses its own folder and never overwrites", async () => { const form = new FormData(); form.set("image", await photo()); form.set("usage", "hero"); form.set("folder", "tenant-b"); const result = await storeWebsiteImage(form); expect(m.upload).toHaveBeenCalledWith(expect.stringMatching(/^data:image\/webp;base64,/), expect.objectContaining({ public_id: expect.stringMatching(/^puragenda_websites\/tenant-a\//), overwrite: false })); expect(result).toMatchObject({ secureUrl: asset.secureUrl, width: 128, format: "webp" }); expect(m.create.mock.calls[0][0].data.websiteId).toBe("website-a"); });
  it("keeps strings from the V1 snapshot but forbids newly pasted unowned images", async () => { const config = { ...emptyBellaConfig(), heroImage: asset.secureUrl }; const db = { websiteMedia: { findMany: m.find } } as unknown as Prisma.TransactionClient; await validateWebsiteAssets(db, "website-a", config, config); expect(m.find).not.toHaveBeenCalled(); m.find.mockResolvedValue([]); await expect(validateWebsiteAssets(db, "website-a", config, emptyBellaConfig())).rejects.toThrow("pertenece"); expect(m.find).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ websiteId: "website-a", deletedAt: null }) })); });
  it("accepts owned replacement refs and rejects tampered or foreign asset metadata", async () => { m.find.mockResolvedValue([asset]); const db = { websiteMedia: { findMany: m.find } } as unknown as Prisma.TransactionClient; const config = { ...emptyBellaConfig(), heroImage: asset.secureUrl, mediaAssets: [asset] }; await validateWebsiteAssets(db, "website-a", config, emptyBellaConfig()); await expect(validateWebsiteAssets(db, "website-a", { ...config, mediaAssets: [{ ...asset, id: "asset-b" }] }, emptyBellaConfig())).rejects.toThrow("pertenece"); await expect(validateWebsiteAssets(db, "website-a", { ...config, mediaAssets: [{ ...asset, bytes: 1 }] }, emptyBellaConfig())).rejects.toThrow("pertenece"); });
  it("cannot delete another tenant's image or any still-published photo", async () => { m.find.mockResolvedValue(null); await expect(deleteWebsiteAsset("asset-b")).rejects.toThrow("encontrada"); expect(m.find).toHaveBeenCalledWith(expect.objectContaining({ where: { id: "asset-b", deletedAt: null, website: { businessId: "tenant-a" } } })); m.find.mockResolvedValue({ ...asset, website: { draftConfig: emptyBellaConfig(), publishedConfig: { ...emptyBellaConfig(), heroImage: asset.secureUrl } } }); await expect(deleteWebsiteAsset("asset-a")).rejects.toThrow("publicado"); expect(m.destroy).not.toHaveBeenCalled(); });
  it("deletes an unreferenced asset through its server-owned public ID", async () => { m.find.mockResolvedValue({ ...asset, provider: "cloudinary", website: { draftConfig: emptyBellaConfig(), publishedConfig: null } }); m.update.mockResolvedValue({ ...asset, provider: "cloudinary" }); await deleteWebsiteAsset("asset-a"); expect(m.destroy).toHaveBeenCalledWith(asset.publicId, { invalidate: true }); });
});
