"use client";
/* eslint-disable react-hooks/set-state-in-effect -- Preview and reveal effects synchronize external iframe/DOM state. */
import { useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import dynamic from "next/dynamic";
import { Cormorant_Garamond, DM_Sans } from "next/font/google";
import type { WebsiteView } from "../../types";
import type { RitualConfig } from "./config";
import { ritualTokens } from "./palettes";
import { ritualGallery, ritualGalleryWindow, ritualServiceLimit } from "./gallery";
import { PREVIEW_PROTOCOL, trustedPreviewSender } from "../../preview-transport";
import { parseRitualPreview } from "./preview";
import { dateKey, money } from "../../booking/validation";
import Media from "./Media";
import { Provider } from "./Context";
import s from "./ritual.module.css";
const Booking = dynamic(() => import("./Booking"));
const display = Cormorant_Garamond({ subsets: ["latin"], variable: "--ritual-display", display: "swap", preload: false, weight: ["400", "500", "600"] });
const body = DM_Sans({ subsets: ["latin"], variable: "--ritual-body", display: "swap", preload: false });
type View = WebsiteView<RitualConfig>;

export default function Ritual({ view: initial }: { view: View }) {
  const [draft, setDraft] = useState(initial.config), sequence = useRef(-1);
  useEffect(() => { if (!initial.preview || window.parent === window) return; const receive = (event: MessageEvent) => { if (!trustedPreviewSender(event, window.parent, window.location.origin)) return; const parsed = parseRitualPreview(event.data); if (!parsed.success || parsed.data.sequence < sequence.current) return; sequence.current = parsed.data.sequence; setDraft(parsed.data.config); if (parsed.data.focus) requestAnimationFrame(() => document.querySelector(`[data-website-field="${parsed.data.focus}"]`)?.scrollIntoView({ behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "instant" : "smooth", block: "center" })); }; window.addEventListener("message", receive); window.parent.postMessage({ protocol: PREVIEW_PROTOCOL, type: "ready" }, window.location.origin); return () => window.removeEventListener("message", receive); }, [initial.preview]);
  const view = { ...initial, config: initial.preview ? draft : initial.config };
  return <Provider view={view}><Page view={view} /></Provider>;
}

function Page({ view }: { view: View }) {
  const { config: c, business: b, catalog } = view, copy = c.copy, t = ritualTokens(c);
  const [active, setActive] = useState(catalog.services[0]?.id ?? ""), [bookingService, setBookingService] = useState<string>(), [bookingOpen, setBookingOpen] = useState(false), [category, setCategory] = useState("all"), [showAll, setShowAll] = useState(catalog.services.length <= 8), [galleryFilter, setGalleryFilter] = useState("all"), [galleryCursor, setGalleryCursor] = useState(0), [lightbox, setLightbox] = useState<number | null>(null), [staffCursor, setStaffCursor] = useState(0), [seen, setSeen] = useState(false);
  const featuredService = catalog.services.find(item => item.id === c.featuredServiceId) ?? catalog.services[0];
  const service = catalog.services.find(item => item.id === active) ?? featuredService;
  const categories = useMemo(() => Array.from(new Map(catalog.services.map(item => [item.categoryId || item.category || "general", item.category || "Tratamientos"])).entries()), [catalog.services]);
  const categoryServices = category === "all" ? catalog.services : catalog.services.filter(item => (item.categoryId || item.category || "general") === category);
  const visibleServices = showAll ? categoryServices : categoryServices.slice(0, ritualServiceLimit(categoryServices.length));
  const gallery = ritualGallery(c, catalog), filteredGallery = galleryFilter === "all" ? gallery : gallery.filter(item => item.categoryIds?.includes(galleryFilter));
  const galleryWindow = ritualGalleryWindow(filteredGallery, galleryCursor, 6);
  const staff = catalog.staff.filter(person => c.staffEditorial[person.id]?.visible !== false), staffWindow = staff.slice(staffCursor, staffCursor + Math.min(3, staff.length));
  useEffect(() => { const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.setAttribute("data-seen", "true"); observer.unobserve(entry.target); } }), { threshold: .1 }); document.querySelectorAll("[data-ritual-reveal]").forEach(el => observer.observe(el)); setSeen(true); return () => observer.disconnect(); }, []);
  useEffect(() => { if (lightbox === null) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") setLightbox(null); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [lightbox]);
  const styles = { "--ritual-background": t.background, "--ritual-surface": t.surface, "--ritual-text": t.text, "--ritual-muted": t.muted, "--ritual-accent": t.accent, "--ritual-accent-contrast": t.accentContrast, "--ritual-line": t.line, "--ritual-warm": t.warm, "--ritual-dark": t.dark } as CSSProperties;
  const reserve = (id?: string) => { setBookingService(id); setBookingOpen(true); requestAnimationFrame(() => document.getElementById("booking")?.scrollIntoView({ behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "instant" : "smooth" })); };
  const nav = [{ id: "services", label: copy.nav.services, show: !!catalog.services.length }, { id: "staff", label: copy.nav.staff, show: c.visibility.showStaff && !!staff.length }, { id: "gallery", label: copy.nav.gallery, show: c.visibility.showGallery && !!gallery.length }, { id: "about", label: copy.nav.about, show: c.visibility.showAbout && (!!c.about || !!c.aboutImage) }, { id: "faq", label: copy.nav.faq, show: c.visibility.showFaq && !!c.faq.length }];
  return <main id="studio-root" className={`${s.root} ${display.variable} ${body.variable}`} style={styles} data-ready={seen}>
    <header className={s.header}><a className={s.brand} href="#top">{c.logo || b.logo ? <Media src={c.logo || b.logo!} alt={c.displayName || b.name} width={140} height={42} /> : c.displayName || b.name}</a><nav className={s.nav} aria-label="Navegación principal">{nav.filter(x => x.show).map(x => <a key={x.id} href={`#${x.id}`}>{x.label}</a>)}</nav><button className={s.action} onClick={() => reserve()}>{copy.nav.reserve}</button></header>
    <section id="top" className={s.hero} data-ritual-reveal data-website-field="heroImage"><div className={s.heroMeta}><span>{c.brandEyebrow}</span><span>{b.address || b.name}</span></div><div className={s.heroCopy}><p className={s.eyebrow}>{c.brandEyebrow}</p><h1 data-long={c.headline.length > 55 ? "true" : undefined} data-website-field="headline">{c.headline}</h1><p className={s.heroIntro} data-website-field="intro">{c.intro}</p><div className={s.heroActions}><button className={s.action} onClick={() => reserve()}>{copy.reserve}</button>{gallery.length && c.visibility.showGallery ? <a className={`${s.action} ${s.outline}`} href="#gallery">{copy.secondary}</a> : null}</div></div><div className={s.heroVisual}>{c.heroImage ? <figure className={s.heroPhoto}><Media src={c.heroImage} alt={c.heroCaption || c.displayName || b.name} fill sizes="(max-width: 800px) 100vw, 55vw" loading="eager" fetchPriority="high" /><figcaption className={s.heroCaption}>{c.heroCaption}</figcaption></figure> : <div className={s.heroPhoto} aria-label="Añade una fotografía en Portada" />}</div><span className={s.heroStamp}>MATERIAL · TOUCH · PAUSE</span></section>
    {c.visibility.showFeatured && featuredService ? <section className={`${s.section} ${s.featured}`} data-ritual-reveal><div><p className={s.kicker}>{copy.featuredEyebrow}</p><h2>{copy.featuredTitle}</h2><p>{featuredService.description}</p><button className={s.textAction} onClick={() => reserve(featuredService.id)}>{copy.serviceAction} <span>↗</span></button></div><div className={s.featuredMeta}><strong>{featuredService.name}</strong><span>{featuredService.duration} min · {money(featuredService.price, catalog.business.currency)}</span></div></section> : null}
    {catalog.services.length ? <section id="services" className={s.section} data-ritual-reveal data-website-field="servicesTitle"><SectionHeading number="01" title={copy.servicesTitle} note={copy.servicesNote} /><div className={s.serviceExplorer}><div className={s.serviceControls}>{categories.length > 1 ? <div className={s.categoryTabs} role="tablist" aria-label="Categorías de tratamientos"><button role="tab" aria-selected={category === "all"} onClick={() => { setCategory("all"); setActive(catalog.services[0]?.id ?? ""); }}>Todos</button>{categories.map(([id, label]) => <button key={id} role="tab" aria-selected={category === id} onClick={() => { setCategory(id); setActive(catalog.services.find(item => (item.categoryId || item.category || "general") === id)?.id ?? ""); }}>{label}</button>)}</div> : null}<div className={s.serviceList}>{visibleServices.map((item, i) => <button className={s.serviceButton} key={item.id} aria-pressed={item.id === service?.id} onClick={() => setActive(item.id)}><span>{String(i + 1).padStart(2, "0")}</span><strong>{item.name}</strong><small>{item.duration} min<br />{money(item.price, catalog.business.currency)}</small></button>)}</div>{categoryServices.length > visibleServices.length ? <button className={s.moreButton} onClick={() => setShowAll(value => !value)}>{showAll ? "Mostrar menos" : copy.allServices}</button> : null}</div>{service ? <div className={s.serviceFeature} key={service.id}>{service.image ? <div className={s.servicePhoto}><Media src={service.image} alt={service.name} fill sizes="(max-width: 800px) 100vw, 42vw" /></div> : <div className={s.serviceNoPhoto}>{service.name}</div>}<div className={s.serviceDetail} aria-live="polite"><p className={s.kicker}>{service.category || "Tratamiento"}</p><h3>{service.name}</h3><p>{service.description}</p><p className={s.serviceFacts}>{service.duration} min · {money(service.price, catalog.business.currency)}</p><button className={s.action} onClick={() => reserve(service.id)}>{copy.serviceAction}</button></div></div> : null}</div></section> : null}
    {c.visibility.showSensory && (copy.pauseTitle || copy.pauseBody) ? <section className={`${s.pause} ${s.section}`} data-ritual-reveal><div className={s.pauseMark}>02</div><div><p className={s.kicker}>{c.sensorial.eyebrow}</p><h2>{copy.pauseTitle}</h2><p>{copy.pauseBody || c.sensorial.body}</p></div><div className={s.pauseAside}><span>Tu siguiente paso</span><button className={s.outlineAction} onClick={() => reserve()}>{copy.reserve} <span>↗</span></button></div></section> : null}
    {c.visibility.showStaff && staff.length ? <section id="staff" className={`${s.section} ${s.staffSection}`} data-ritual-reveal><SectionHeading number="03" title={copy.staffTitle} note={copy.staffNote} /><div className={s.staffRail}><div className={s.staffGrid}>{staffWindow.map(person => { const editorial = c.staffEditorial[person.id]; return <article className={s.person} key={person.id}><div className={s.personPhoto}>{person.image ? <Media src={person.image} alt={person.name} fill sizes="(max-width: 600px) 86vw, 29vw" /> : <span className={s.initials}>{person.name.split(/\s+/).slice(0, 2).map(word => word[0]).join("")}</span>}</div><h3>{person.name}</h3><p>{editorial?.label || "Profesional"}</p><small>{editorial?.note || catalog.services.filter(item => !person.serviceIds.length || person.serviceIds.includes(item.id)).slice(0, 3).map(item => item.name).join(" · ")}</small></article>; })}</div>{staff.length > 3 ? <div className={s.railControls}><button onClick={() => setStaffCursor(Math.max(0, staffCursor - 1))} disabled={staffCursor === 0} aria-label="Profesional anterior">←</button><span>{String(staffCursor + 1).padStart(2, "0")} / {String(Math.max(1, staff.length - 2)).padStart(2, "0")}</span><button onClick={() => setStaffCursor(Math.min(staff.length - 3, staffCursor + 1))} disabled={staffCursor >= staff.length - 3} aria-label="Profesional siguiente">→</button></div> : null}</div></section> : null}
    {c.visibility.showGallery && gallery.length ? <section id="gallery" className={`${s.section} ${s.gallerySection}`} data-ritual-reveal data-website-field="gallery"><SectionHeading number="04" title={copy.galleryTitle} note={copy.galleryNote} />{c.galleryCategories.length && gallery.some(item => item.categoryIds?.length) ? <div className={s.filters}><button aria-pressed={galleryFilter === "all"} onClick={() => { setGalleryFilter("all"); setGalleryCursor(0); }}>{copy.galleryAll}</button>{c.galleryCategories.map(cat => <button key={cat.id} aria-pressed={galleryFilter === cat.id} onClick={() => { setGalleryFilter(cat.id); setGalleryCursor(0); }}>{cat.label}</button>)}</div> : null}<div className={s.galleryRail}><div className={s.gallery}>{galleryWindow.items.map((item, i) => <button className={s.galleryItem} key={`${item.image}-${galleryWindow.cursor}-${i}`} onClick={() => setLightbox((galleryWindow.cursor + i) % Math.max(1, filteredGallery.length))} aria-label={`Ver ${item.name || item.alt}`}><Media src={item.image} alt={item.alt || item.name} fill sizes="(max-width: 800px) 82vw, 28vw" style={{ objectPosition: item.focal }} /><span className={s.galleryLabel}>{item.name || item.alt}</span></button>)}</div>{galleryWindow.total > 6 ? <div className={s.railControls}><button onClick={() => setGalleryCursor(galleryCursor - 1)} aria-label="Imagen anterior">←</button><span>{String(galleryWindow.cursor + 1).padStart(2, "0")} / {String(galleryWindow.total).padStart(2, "0")}</span><button onClick={() => setGalleryCursor(galleryCursor + 1)} aria-label="Imagen siguiente">→</button></div> : null}</div></section> : null}
    {c.visibility.showAbout && (c.about || c.aboutImage) ? <section id="about" className={`${s.section} ${s.about}`} data-ritual-reveal data-website-field="about"><div className={s.aboutCopy}><SectionHeading number="05" title={copy.aboutTitle} /><p>{c.about}</p><div className={s.aboutDetails}><span>{b.address || "Ubicación por confirmar"}</span><span>{b.hours?.filter(row => row.isOpen).length ? `${b.hours.filter(row => row.isOpen).length} días abiertos` : "Agenda online"}</span></div></div>{c.aboutImage ? <div className={s.aboutPhoto}><Media src={c.aboutImage} alt={copy.aboutTitle} fill sizes="(max-width: 800px) 100vw, 46vw" /></div> : null}</section> : null}
    {c.visibility.showFaq && c.faq.length ? <section id="faq" className={`${s.section} ${s.faq}`} data-ritual-reveal><SectionHeading number="06" title={copy.faqTitle} />{c.faq.map(item => <details key={item.id}><summary>{item.question}<span>+</span></summary><p>{item.answer}</p></details>)}</section> : null}
    <section id="booking" className={`${s.section} ${s.booking}`} data-website-field="booking"><SectionHeading number="07" title={copy.bookingTitle} note={copy.bookingNote} />{bookingOpen ? <Booking key={bookingService || "all"} catalog={catalog} today={dateKey(new Date(), catalog.business.timezone)} initialServiceId={bookingService} copy={{ steps: copy.bookingSteps, title: copy.bookingTitle, note: copy.bookingNote, action: copy.reserve }} /> : <div className={s.bookingPrompt}><p>Elige un tratamiento y consulta los horarios reales disponibles.</p><button className={s.action} onClick={() => reserve()}>{copy.reserve}</button></div>}</section>
    <footer className={`${s.section} ${s.footer}`} data-ritual-reveal data-website-field="contact"><p className={s.footerStatement}>{copy.footerStatement || c.displayName || b.name}</p><div className={s.footerGrid}><div><h2>{copy.contactTitle}</h2>{b.address ? <p>{b.address}</p> : null}{b.mapsUrl ? <a href={b.mapsUrl} target="_blank" rel="noopener noreferrer">{copy.mapsLabel}</a> : null}{c.phone ? <a href={`tel:${c.phone}`}>{c.phone}</a> : null}{c.contactEmail ? <a href={`mailto:${c.contactEmail}`}>{c.contactEmail}</a> : null}</div>{b.hours?.length ? <div><h2>{copy.hoursTitle}</h2><div className={s.hours}>{[...b.hours].sort((a, z) => a.dayOfWeek - z.dayOfWeek).map(row => <div key={row.dayOfWeek}><span>{["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"][row.dayOfWeek]}</span><span>{row.isOpen ? `${row.startTime} — ${row.endTime}` : "Cerrado"}</span></div>)}</div></div> : null}<div>{c.instagram ? <a href={c.instagram} target="_blank" rel="noopener noreferrer">Instagram</a> : null}{c.facebook ? <a href={c.facebook} target="_blank" rel="noopener noreferrer">Facebook</a> : null}<button className={s.action} onClick={() => reserve()}>{copy.reserve}</button></div></div><div className={s.colophon}><span>{c.displayName || b.name}</span><a href="https://puragenda.cl" target="_blank" rel="noopener noreferrer">Sitio y reservas con Puragenda</a></div></footer>
    {lightbox !== null && filteredGallery[lightbox] ? <div className={s.lightbox} role="dialog" aria-modal="true" aria-label="Galería ampliada" onClick={() => setLightbox(null)}><button className={s.lightboxClose} onClick={() => setLightbox(null)} aria-label="Cerrar">×</button><button className={s.lightboxNav} onClick={event => { event.stopPropagation(); setLightbox((lightbox - 1 + filteredGallery.length) % filteredGallery.length); }} aria-label="Imagen anterior">←</button><div className={s.lightboxImage} onClick={event => event.stopPropagation()}><Media src={filteredGallery[lightbox].image} alt={filteredGallery[lightbox].alt || filteredGallery[lightbox].name} fill sizes="90vw" /></div><button className={s.lightboxNav} onClick={event => { event.stopPropagation(); setLightbox((lightbox + 1) % filteredGallery.length); }} aria-label="Imagen siguiente">→</button></div> : null}
  </main>;
}
function SectionHeading({ number, title, note }: { number: string; title: string; note?: string }) { return <div className={s.sectionHeader}><span>{number} /</span><h2>{title}</h2>{note ? <p>{note}</p> : null}</div>; }
