"use client";
/* eslint-disable react-hooks/set-state-in-effect -- Preview and reveal effects synchronize external iframe/DOM state. */
import { useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import dynamic from "next/dynamic";
import { Cormorant_Garamond, DM_Sans } from "next/font/google";
import type { WebsiteView } from "../../types";
import type { RitualConfig } from "./config";
import { ritualTokens } from "./palettes";
import { ritualGallery, ritualGalleryCategories, ritualServiceLimit } from "./gallery";
import { PREVIEW_PROTOCOL, trustedPreviewSender } from "../../preview-transport";
import { parseRitualPreview } from "./preview";
import { dateKey, money } from "../../booking/validation";
import Media from "./Media";
import Rail from "./Rail";
import Lightbox from "./Lightbox";
import { Provider } from "./Context";
import s from "./ritual.module.css";
const Booking = dynamic(() => import("./Booking"));
const display = Cormorant_Garamond({ subsets: ["latin"], variable: "--ritual-display", display: "swap", preload: false, weight: ["400", "500", "600"] });
const body = DM_Sans({ subsets: ["latin"], variable: "--ritual-body", display: "swap", preload: false });
type View = WebsiteView<RitualConfig>;

export default function Ritual({ view: initial }: { view: View }) {
  const [draft, setDraft] = useState(initial.config), sequence = useRef(-1);
  useEffect(() => { if (!initial.preview || window.parent === window) return; const receive = (event: MessageEvent) => { if (!trustedPreviewSender(event, window.parent, window.location.origin)) return; const parsed = parseRitualPreview(event.data, window.location.origin); if (!parsed.success || parsed.data.sequence < sequence.current) return; sequence.current = parsed.data.sequence; setDraft(parsed.data.config); if (parsed.data.focus) requestAnimationFrame(() => document.querySelector(`[data-website-field="${parsed.data.focus}"]`)?.scrollIntoView({ behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "instant" : "smooth", block: "center" })); }; window.addEventListener("message", receive); window.parent.postMessage({ protocol: PREVIEW_PROTOCOL, type: "ready" }, window.location.origin); return () => window.removeEventListener("message", receive); }, [initial.preview]);
  const view = { ...initial, config: initial.preview ? draft : initial.config };
  return <Provider view={view}><Page view={view} /></Provider>;
}

function Page({ view }: { view: View }) {
  const { config: c, business: b, catalog } = view, copy = c.copy, t = ritualTokens(c);
  const [active, setActive] = useState(catalog.services[0]?.id ?? ""), [bookingService, setBookingService] = useState<string>(), [bookingOpen, setBookingOpen] = useState(false), [category, setCategory] = useState("all"), [visibleCount, setVisibleCount] = useState(ritualServiceLimit(catalog.services.length)), [galleryFilter, setGalleryFilter] = useState("all"), [lightbox, setLightbox] = useState<number | null>(null), [lightboxOrigin, setLightboxOrigin] = useState<HTMLElement | null>(null), [seen, setSeen] = useState(false);
  const featuredService = catalog.services.find(item => item.id === c.featuredServiceId) ?? catalog.services[0];
  const service = catalog.services.find(item => item.id === active) ?? featuredService;
  const categories = useMemo(() => Array.from(new Map(catalog.services.map(item => [item.categoryId || item.category || "general", item.category || "Tratamientos"])).entries()), [catalog.services]);
  const categoryServices = category === "all" ? catalog.services : catalog.services.filter(item => (item.categoryId || item.category || "general") === category);
  const visibleServices = categoryServices.slice(0, Math.min(categoryServices.length, visibleCount));
  const gallery = ritualGallery(c, catalog), filteredGallery = galleryFilter === "all" ? gallery : gallery.filter(item => item.categoryIds?.includes(galleryFilter));
  const galleryCategories = ritualGalleryCategories(c, catalog);
  const staff = catalog.staff.filter(person => c.staffEditorial[person.id]?.visible !== false);
  useEffect(() => { const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.setAttribute("data-seen", "true"); observer.unobserve(entry.target); } }), { threshold: .1 }); document.querySelectorAll("[data-ritual-reveal]").forEach(el => observer.observe(el)); setSeen(true); return () => observer.disconnect(); }, []);
  const styles = { "--ritual-background": t.background, "--ritual-surface": t.surface, "--ritual-text": t.text, "--ritual-muted": t.muted, "--ritual-accent": t.accent, "--ritual-accent-contrast": t.accentContrast, "--ritual-line": t.line, "--ritual-warm": t.warm, "--ritual-dark": t.dark } as CSSProperties;
  const reserve = (id?: string) => { setBookingService(id); setBookingOpen(true); requestAnimationFrame(() => document.getElementById("booking")?.scrollIntoView({ behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "instant" : "smooth" })); };
  const nav = [{ id: "services", label: copy.nav.services, show: !!catalog.services.length }, { id: "staff", label: copy.nav.staff, show: c.visibility.showStaff && !!staff.length }, { id: "gallery", label: copy.nav.gallery, show: c.visibility.showGallery && !!gallery.length }, { id: "about", label: copy.nav.about, show: c.visibility.showAbout && (!!c.about || !!c.aboutImage) }, { id: "faq", label: copy.nav.faq, show: c.visibility.showFaq && !!c.faq.length }];
  return <main id="studio-root" className={`${s.root} ${display.variable} ${body.variable}`} style={styles} data-ready={seen}>
    <header className={s.header}><a className={s.brand} href="#top">{c.logo || b.logo ? <Media src={c.logo || b.logo!} alt={c.displayName || c.brandTitle || b.name} width={140} height={42} /> : c.displayName || c.brandTitle || b.name}</a><nav className={s.nav} aria-label="Navegación principal">{nav.filter(x => x.show).map(x => <a key={x.id} href={`#${x.id}`}>{x.label}</a>)}</nav><button className={s.action} onClick={() => reserve()}>{copy.nav.reserve}</button></header>
    <section id="top" className={s.hero} data-ritual-reveal data-website-field="heroImage"><div className={s.heroMeta}><span>{c.brandEyebrow}</span>{b.address ? <span>{b.address}</span> : null}</div><div className={s.heroCopy}><p className={s.eyebrow}>{c.brandEyebrow}</p><h1 data-long={c.headline.length > 55 ? "true" : undefined} data-website-field="headline">{c.headline}</h1><p className={s.heroIntro} data-website-field="intro">{c.intro}</p><div className={s.heroActions}><button className={s.action} onClick={() => reserve()}>{copy.reserve}</button>{gallery.length && c.visibility.showGallery ? <a className={`${s.action} ${s.outline}`} href="#gallery">{copy.secondary}</a> : null}</div></div><div className={s.heroVisual}>{c.heroImage ? <figure className={s.heroPhoto}><Media src={c.heroImage} alt={c.heroCaption || c.displayName || c.brandTitle || b.name} fill sizes="(max-width: 800px) 100vw, 55vw" loading="eager" fetchPriority="high" /><figcaption className={s.heroCaption}>{c.heroCaption}</figcaption></figure> : <div className={s.heroPhoto} aria-label="Añade una fotografía en Portada" />}</div>{copy.heroStamp ? <span className={s.heroStamp}>{copy.heroStamp}</span> : null}</section>
    {c.visibility.showFeatured && featuredService ? <section className={`${s.section} ${s.featured}`} data-ritual-reveal><div><p className={s.kicker}>{copy.featuredEyebrow}</p><h2>{copy.featuredTitle}</h2><p>{featuredService.description}</p><button className={s.textAction} onClick={() => reserve(featuredService.id)}>{copy.serviceAction} <span>↗</span></button></div><div className={s.featuredMeta}><strong>{featuredService.name}</strong><span>{featuredService.duration} min · {money(featuredService.price, catalog.business.currency)}</span></div></section> : null}
    {catalog.services.length ? <section id="services" className={s.section} data-ritual-reveal data-website-field="servicesTitle"><SectionHeading number="01" title={copy.servicesTitle} note={copy.servicesNote} /><div className={s.serviceExplorer}><div className={s.serviceControls}>{categories.length > 1 ? <div className={s.categoryTabs} role="tablist" aria-label="Categorías de tratamientos"><button role="tab" aria-selected={category === "all"} onClick={() => { setCategory("all"); setVisibleCount(ritualServiceLimit(catalog.services.length)); setActive(catalog.services[0]?.id ?? ""); }}>{copy.servicesAll}</button>{categories.map(([id, label]) => <button key={id} role="tab" aria-selected={category === id} onClick={() => { const next = catalog.services.filter(item => (item.categoryId || item.category || "general") === id); setCategory(id); setVisibleCount(ritualServiceLimit(next.length)); setActive(next[0]?.id ?? ""); }}>{label}</button>)}</div> : null}<div className={s.serviceList}>{visibleServices.map((item, i) => <button className={s.serviceButton} key={item.id} aria-pressed={item.id === service?.id} onClick={() => setActive(item.id)}><span>{String(i + 1).padStart(2, "0")}</span><strong>{item.name}</strong><small>{item.duration} min<br />{money(item.price, catalog.business.currency)}</small></button>)}</div>{categoryServices.length > visibleServices.length ? <button className={s.moreButton} onClick={() => setVisibleCount(count => Math.min(categoryServices.length, count + 6))}>{copy.allServices.replace("{count}", String(Math.min(6, categoryServices.length - visibleServices.length)))}</button> : null}</div>{service ? <div className={s.serviceFeature} key={service.id}>{service.image ? <div className={s.servicePhoto}><Media src={service.image} alt={service.name} fill sizes="(max-width: 800px) 100vw, 42vw" /></div> : <div className={s.serviceNoPhoto}>{service.name}</div>}<div className={s.serviceDetail} aria-live="polite"><p className={s.kicker}>{service.category || copy.serviceDefaultLabel}</p><h3>{service.name}</h3><p>{service.description}</p><p className={s.serviceFacts}>{service.duration} min · {money(service.price, catalog.business.currency)}</p><button className={s.action} onClick={() => reserve(service.id)}>{copy.serviceAction}</button></div></div> : null}</div></section> : null}
    {c.visibility.showSensory && (c.sensorial.title || c.sensorial.body) ? <section className={`${s.pause} ${s.section}`} data-ritual-reveal><div className={s.pauseMark}>02</div><div><p className={s.kicker}>{c.sensorial.eyebrow}</p><h2>{c.sensorial.title}</h2><p>{c.sensorial.body}</p></div><div className={s.pauseAside}><span>{copy.pauseLabel}</span><button className={s.outlineAction} onClick={() => reserve()}>{copy.pauseAction} <span>↗</span></button></div></section> : null}
    {c.visibility.showStaff && staff.length ? <section id="staff" className={`${s.section} ${s.staffSection}`} data-ritual-reveal><SectionHeading number="03" title={copy.staffTitle} note={copy.staffNote} /><Rail items={staff} size={3} kind="staff" label={copy.nav.staff} render={(person) => { const editorial = c.staffEditorial[person.id]; return <article className={s.person} key={person.id}><div className={s.personPhoto}>{person.image ? <Media src={person.image} alt={person.name} fill sizes="(max-width: 600px) 86vw, 29vw" /> : <span className={s.initials}>{person.name.split(/\s+/).slice(0, 2).map(word => word[0]).join("")}</span>}</div><h3>{person.name}</h3><p>{editorial?.label || copy.staffDefaultLabel}</p><small>{editorial?.note || catalog.services.filter(item => !person.serviceIds.length || person.serviceIds.includes(item.id)).slice(0, 3).map(item => item.name).join(" · ")}</small></article>; }} /></section> : null}
    {c.visibility.showGallery && gallery.length ? <section id="gallery" className={`${s.section} ${s.gallerySection}`} data-ritual-reveal data-website-field="gallery"><SectionHeading number="04" title={copy.galleryTitle} note={copy.galleryNote} />{galleryCategories.length && gallery.some(item => item.categoryIds?.length) ? <div className={s.filters}><button aria-pressed={galleryFilter === "all"} onClick={() => setGalleryFilter("all")}>{copy.galleryAll}</button>{galleryCategories.map(cat => <button key={cat.id} aria-pressed={galleryFilter === cat.id} onClick={() => setGalleryFilter(cat.id)}>{cat.label}</button>)}</div> : null}<Rail items={filteredGallery} size={6} kind="gallery" label={copy.galleryTitle} render={(item, index) => <button className={s.galleryItem} key={`${item.image}-${index}`} onClick={event => { setLightbox(index); setLightboxOrigin(event.currentTarget); }} aria-label={`Ver ${item.name || item.alt}`}><Media src={item.image} alt={item.alt || item.name} fill sizes="(max-width: 800px) 82vw, 28vw" style={{ objectPosition: item.focal }} /><span className={s.galleryLabel}>{item.name || item.alt}</span></button>} /></section> : null}
    {c.visibility.showAbout && (c.about || c.aboutImage) ? <section id="about" className={`${s.section} ${s.about}`} data-ritual-reveal data-website-field="about"><div className={s.aboutCopy}><SectionHeading number="05" title={copy.aboutTitle} /><p>{c.about}</p><div className={s.aboutDetails}>{b.address ? <span>{b.address}</span> : null}{b.hours?.filter(row => row.isOpen).length ? <span>{`${b.hours.filter(row => row.isOpen).length} días abiertos`}</span> : null}</div></div>{c.aboutImage ? <div className={s.aboutPhoto}><Media src={c.aboutImage} alt={copy.aboutTitle} fill sizes="(max-width: 800px) 100vw, 46vw" /></div> : null}</section> : null}
    {c.visibility.showFaq && c.faq.length ? <section id="faq" className={`${s.section} ${s.faq}`} data-ritual-reveal><SectionHeading number="06" title={copy.faqTitle} />{c.faq.map(item => <details key={item.id}><summary>{item.question}<span>+</span></summary><p>{item.answer}</p></details>)}</section> : null}
    <section id="booking" className={`${s.section} ${s.booking}`} data-website-field="booking"><SectionHeading number="07" title={copy.bookingTitle} note={copy.bookingNote} />{bookingOpen ? <Booking key={bookingService || "all"} catalog={catalog} today={dateKey(new Date(), catalog.business.timezone)} initialServiceId={bookingService} copy={{ steps: copy.bookingSteps, title: copy.bookingTitle, note: copy.bookingNote, action: copy.reserve }} /> : <div className={s.bookingPrompt}><p>{copy.bookingPrompt}</p><button className={s.action} onClick={() => reserve()}>{copy.reserve}</button></div>}</section>
    <footer className={`${s.section} ${s.footer}`} data-ritual-reveal data-website-field="contact"><p className={s.footerStatement}>{copy.footerStatement || c.displayName || c.brandTitle || b.name}</p><div className={s.footerGrid}><div><h2>{copy.contactTitle}</h2>{b.address ? <p>{b.address}</p> : null}{b.mapsUrl ? <a href={b.mapsUrl} target="_blank" rel="noopener noreferrer">{copy.mapsLabel}</a> : null}{c.phone ? <a href={`tel:${c.phone}`}>{c.phone}</a> : null}{c.contactEmail ? <a href={`mailto:${c.contactEmail}`}>{c.contactEmail}</a> : null}</div>{b.hours?.length ? <div><h2>{copy.hoursTitle}</h2><div className={s.hours}>{[...b.hours].sort((a, z) => a.dayOfWeek - z.dayOfWeek).map(row => <div key={row.dayOfWeek}><span>{["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"][row.dayOfWeek]}</span><span>{row.isOpen ? `${row.startTime} — ${row.endTime}` : "Cerrado"}</span></div>)}</div></div> : null}<div>{c.instagram ? <a href={c.instagram} target="_blank" rel="noopener noreferrer">Instagram</a> : null}{c.facebook ? <a href={c.facebook} target="_blank" rel="noopener noreferrer">Facebook</a> : null}<button className={s.action} onClick={() => reserve()}>{copy.reserve}</button></div></div><div className={s.colophon}><span>{c.displayName || c.brandTitle || b.name}</span><a href="https://puragenda.cl" target="_blank" rel="noopener noreferrer">Sitio y reservas con Puragenda</a></div></footer>
    {lightbox !== null ? <Lightbox images={filteredGallery} initial={lightbox} origin={lightboxOrigin} onClose={() => { setLightbox(null); setLightboxOrigin(null); }} /> : null}
  </main>;
}
function SectionHeading({ number, title, note }: { number: string; title: string; note?: string }) { return <div className={s.sectionHeader}><span>{number} /</span><h2>{title}</h2>{note ? <p>{note}</p> : null}</div>; }
