import { afterEach, describe, expect, it, vi } from "vitest";
import { DraftAutosave } from "@/websites/autosave";
import { normalizeSocial, reorderGallery } from "@/websites/editor-utils";
import { websiteMetadata } from "@/websites/metadata";
import { bellaConfigSchema } from "@/websites/config";
import { BELLA_PALETTES } from "@/websites/palettes";
import { PREVIEW_PROTOCOL, parsePreviewMessage, trustedPreviewSender } from "@/websites/preview-protocol";
import { fixtureView } from "@/websites/fixtures/views";
afterEach(() => vi.useRealTimers());
describe("visual builder controls and published metadata", () => {
  it("rejects preview messages from sibling frames and foreign origins", () => { const parent = {} as Window; expect(trustedPreviewSender({ origin: "https://app.test", source: parent }, parent, "https://app.test")).toBe(true); expect(trustedPreviewSender({ origin: "https://app.test", source: {} as Window }, parent, "https://app.test")).toBe(false); expect(trustedPreviewSender({ origin: "https://evil.test", source: parent }, parent, "https://app.test")).toBe(false); });
  it("keeps gallery order without mutating the source and rejects invalid moves", () => { const before = ["a", "b", "c"]; expect(reorderGallery(before, 0, 2)).toEqual(["b", "c", "a"]); expect(before).toEqual(["a", "b", "c"]); expect(reorderGallery(before, -1, 1)).toBe(before); });
  it("normalizes Instagram handles and rejects other hosts or credential URLs", () => { expect(normalizeSocial("@daniela.nails", "instagram")).toBe("https://www.instagram.com/daniela.nails"); expect(normalizeSocial("facebook.com/mi.salon", "facebook")).toBe("https://facebook.com/mi.salon"); expect(() => normalizeSocial("https://evil.test/account", "instagram")).toThrow(); expect(() => normalizeSocial("https://user:password@instagram.com/a", "instagram")).toThrow(); });
  it("offers only approved palette colors understood by Bella's schema", () => { for (const palette of BELLA_PALETTES) expect(bellaConfigSchema.parse({ accent: palette.key }).accent).toBe(palette.key); expect(bellaConfigSchema.safeParse({ accent: "custom" }).success).toBe(false); });
  it("automatically describes actual services and categories, without inventing a location", () => { const view = fixtureView("b"); view.config.seoTitle = ""; view.config.seoDescription = ""; view.config.intro = ""; view.business.address = null; const result = websiteMetadata(view); expect(result.title).toContain(view.business.name); expect(result.title).toContain(view.catalog.services[0].category || view.catalog.services[0].name); expect(result.description).not.toContain("Concepción"); expect(result.title.length).toBeLessThanOrEqual(80); });
  it("honors custom Google text and falls back to real content", () => { const view = fixtureView("a"); view.config.seoTitle = "Uñas de Daniela"; view.config.seoDescription = "Tu estudio cercano"; expect(websiteMetadata(view)).toMatchObject({ title: "Uñas de Daniela", description: "Tu estudio cercano" }); view.config.seoDescription = ""; expect(websiteMetadata(view).description).toBe(view.config.intro); });
  it("accepts validated draft messages and same-origin temporary photos only", () => { const message = { protocol: PREVIEW_PROTOCOL, type: "draft", sequence: 3, config: { ...fixtureView("a").config, heroImage: "blob:http://localhost:3005/qa-photo" }, focus: "headline" }; expect(parsePreviewMessage(message, "http://localhost:3005").success).toBe(true); expect(bellaConfigSchema.safeParse(message.config).success).toBe(false); expect(parsePreviewMessage(message, "https://other.test").success).toBe(false); expect(parsePreviewMessage({ ...message, businessId: "tenant-b" }, "http://localhost:3005").success).toBe(false); });
});
describe("draft autosave concurrency", () => {
  it("debounces typing into one save with the last input", async () => { vi.useFakeTimers(); const persist = vi.fn().mockResolvedValue({ revision: 2 }); const draft = new DraftAutosave<string>("first", 1, persist); draft.update("second"); draft.update("third"); await vi.advanceTimersByTimeAsync(650); expect(persist).toHaveBeenCalledTimes(1); expect(persist).toHaveBeenCalledWith("third", 1); expect(draft.getSnapshot()).toMatchObject({ revision: 2, dirty: false, status: "saved" }); draft.dispose(); });
  it("preserves changes made during a save and serializes concurrent flush calls", async () => { let resolve!: (value: { revision: number }) => void; const persist = vi.fn().mockImplementationOnce(() => new Promise(done => { resolve = done; })).mockResolvedValue({ revision: 3 }); const draft = new DraftAutosave<string>("a", 1, persist); draft.update("b"); const first = draft.flush(); draft.update("c"); const second = draft.flush(); resolve({ revision: 2 }); await Promise.all([first, second]); expect(persist.mock.calls).toEqual([["b", 1], ["c", 2]]); expect(draft.getSnapshot().dirty).toBe(false); draft.dispose(); });
  it("keeps failed input, exposes a conflict, and retries without advancing revision", async () => { const persist = vi.fn().mockResolvedValueOnce({ error: "Otra sesión cambió el borrador" }).mockResolvedValue({ revision: 2 }); const draft = new DraftAutosave<string>("a", 1, persist); draft.update("b"); await expect(draft.flush()).rejects.toThrow("Otra sesión"); expect(draft.getSnapshot()).toMatchObject({ revision: 1, dirty: true, status: "error" }); await draft.flush(); expect(persist).toHaveBeenLastCalledWith("b", 1); draft.dispose(); });
  it("holds saving while uploads are in progress and resumes afterwards", async () => { vi.useFakeTimers(); const persist = vi.fn().mockResolvedValue({ revision: 1 }); const draft = new DraftAutosave<string>("a", 0, persist); draft.pause(true); draft.update("b"); await vi.advanceTimersByTimeAsync(2000); expect(persist).not.toHaveBeenCalled(); await expect(draft.flush()).rejects.toThrow("subida"); draft.pause(false); await vi.advanceTimersByTimeAsync(650); expect(persist).toHaveBeenCalledWith("b", 0); draft.dispose(); });
  it("flushes pending input on unmount and supports strict-effect remount", async () => { const persist = vi.fn().mockResolvedValue({ revision: 1 }); const draft = new DraftAutosave<string>("a", 0, persist); draft.dispose(); draft.resume(); draft.update("b"); draft.dispose(); await draft.flush(); expect(persist).toHaveBeenCalledTimes(1); });
});
