"use client";
/* eslint-disable @next/next/no-img-element -- local blob thumbnails are intentionally native. */
import { useState } from "react";
import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import type { RitualConfig } from "@/websites/templates/ritual/config";
import { categoryId, galleryCategoryLabelError } from "@/websites/gallery-categories";
import { reorderGallery } from "@/websites/editor-utils";
import MediaPicker from "./media-picker";
import styles from "./website-builder.module.css";
type Props = { config: RitualConfig; update: (next: (config: RitualConfig) => RitualConfig) => void; busy: (value: boolean) => void; uploadCount: number; onLocal: (key: string, url: string | null) => void; highlight: (filter?: string) => void };
export default function RitualGalleryPanel({ config, update, busy, uploadCount, onLocal, highlight }: Props) {
  const [selected, setSelected] = useState(0), [newCategory, setNewCategory] = useState(""), [categoryDrafts, setCategoryDrafts] = useState<Record<string, string>>({});
  const photo = config.gallery[selected], categories = [...config.galleryCategories].sort((a, b) => a.order - b.order);
  const ids = (item: RitualConfig["gallery"][number]) => item.categoryIds ?? [];
  const setCategories = (next: RitualConfig["galleryCategories"]) => update(previous => ({ ...previous, galleryCategories: next.map((item, order) => ({ ...item, order })), gallery: previous.gallery.map(item => ({ ...item, categoryIds: ids(item).filter(id => next.some(category => category.id === id)) })) }));
  const edit = (patch: Partial<RitualConfig["gallery"][number]>) => update(previous => ({ ...previous, gallery: previous.gallery.map((item, index) => index === selected ? { ...item, ...patch } : item) }));
  const move = (to: number) => { update(previous => ({ ...previous, gallery: reorderGallery(previous.gallery, selected, to) })); setSelected(to); highlight(); };
  const remove = () => { update(previous => ({ ...previous, gallery: previous.gallery.filter((_, index) => index !== selected) })); setSelected(Math.max(0, selected - 1)); };
  function deleteCategory(id: string) { const category = categories.find(item => item.id === id), count = config.gallery.filter(item => ids(item).includes(id)).length; if (!window.confirm(`¿Eliminar “${category?.label}”? ${count} fotos usan esta categoría. Las fotos se conservarán.`)) return; setCategories(categories.filter(item => item.id !== id)); }
  function renameCategory(id: string, label: string) {
    setCategoryDrafts(current => ({ ...current, [id]: label }));
    if (!galleryCategoryLabelError(label, categories, id)) setCategories(categories.map(category => category.id === id ? { ...category, label: label.trim() } : category));
  }
  return <div className={styles.panel}>
    <div className={styles.panelHeading}><h2>Galería</h2><p className={styles.helper}>Organiza hasta 30 imágenes. Una foto puede aparecer en más de una categoría; “Todos” siempre las incluye.</p></div>
    <label className={styles.checkbox}><input type="checkbox" checked={config.visibility.showGallery} onChange={event => update(previous => ({ ...previous, visibility: { ...previous.visibility, showGallery: event.target.checked } }))} />Mostrar galería</label>
    <details open className={styles.googleSettings}><summary>Administrar categorías</summary><div><p className={styles.helper}>Puedes renombrar, reordenar y retirar categorías sin borrar fotos.</p>{categories.map((item, index) => { const label = categoryDrafts[item.id] ?? item.label, error = galleryCategoryLabelError(label, categories, item.id); return <div key={item.id}><div className={styles.row}><input className={styles.textInput} aria-label={`Nombre de categoría ${index + 1}`} aria-invalid={!!error} aria-describedby={error ? `category-error-${item.id}` : undefined} value={label} maxLength={80} onChange={event => renameCategory(item.id, event.target.value)} /><button type="button" className={styles.secondary} aria-label="Subir categoría" disabled={!index} onClick={() => { const next = [...categories]; [next[index - 1], next[index]] = [next[index], next[index - 1]]; setCategories(next); }}><ArrowUp size={13} /></button><button type="button" className={styles.secondary} aria-label="Bajar categoría" disabled={index === categories.length - 1} onClick={() => { const next = [...categories]; [next[index], next[index + 1]] = [next[index + 1], next[index]]; setCategories(next); }}><ArrowDown size={13} /></button><button type="button" className={styles.secondary} aria-label={`Eliminar categoría ${item.label}`} onClick={() => deleteCategory(item.id)}><Trash2 size={13} /></button></div>{error ? <p className={styles.helper} id={`category-error-${item.id}`} role="alert">{error}</p> : null}</div>; })}<div className={styles.row}><input className={styles.textInput} aria-label="Nueva categoría" value={newCategory} maxLength={80} placeholder="Nueva categoría" onChange={event => setNewCategory(event.target.value)} /><button type="button" className={styles.secondary} disabled={!!galleryCategoryLabelError(newCategory, categories) || categories.length >= 20} onClick={() => { const label = newCategory.trim(); setCategories([...categories, { id: categoryId(label, categories.map(item => item.id)), label, order: categories.length }]); setNewCategory(""); }}><Plus size={12} />Añadir</button></div>{newCategory && galleryCategoryLabelError(newCategory, categories) ? <p className={styles.helper} role="alert">{galleryCategoryLabelError(newCategory, categories)}</p> : null}</div></details>
    <div className={styles.gallery}>{config.gallery.map((item, index) => <button type="button" key={`${index}-${item.image}`} className={styles.galleryPhoto} aria-label={`Editar foto ${index + 1}: ${item.name}`} aria-pressed={selected === index} draggable={uploadCount === 0} onDragStart={event => event.dataTransfer.setData("text/plain", String(index))} onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); const from = Number(event.dataTransfer.getData("text/plain")); if (Number.isInteger(from)) { update(previous => ({ ...previous, gallery: reorderGallery(previous.gallery, from, index) })); setSelected(index); } }} onClick={() => { setSelected(index); highlight(); }}><img src={item.image} alt={item.alt || item.name} /><span>{index + 1}</span></button>)}</div>
    {photo ? <div className={styles.divider}><h3>Foto {selected + 1}</h3><label className={styles.field}>Nombre<input maxLength={100} value={photo.name} onChange={event => edit({ name: event.target.value, alt: event.target.value })} /></label><p className={styles.label}>¿Dónde quieres mostrar esta foto?</p><p className={styles.helper}>Puedes elegir más de una categoría.</p><div className={styles.chips}>{categories.map(item => <button type="button" key={item.id} aria-pressed={ids(photo).includes(item.id)} disabled={!ids(photo).includes(item.id) && ids(photo).length >= 8} onClick={() => edit({ categoryIds: ids(photo).includes(item.id) ? ids(photo).filter(id => id !== item.id) : [...ids(photo), item.id] })}>{item.label}</button>)}</div><p className={styles.helper}>{categories.filter(item => ids(photo).includes(item.id)).map(item => item.label).join(" · ") || "Solo en Todos"}</p><MediaPicker label="Foto seleccionada" value={photo.image} usage="gallery" onBusy={busy} onLocalPreview={url => onLocal(`gallery.${selected}`, url)} onFocus={() => highlight()} onChange={(url, asset) => { if (!url) remove(); else update(previous => ({ ...previous, gallery: previous.gallery.map((item, index) => index === selected ? { ...item, image: url } : item), ...(asset ? { mediaAssets: [...(previous.mediaAssets ?? []).filter(entry => entry.id !== asset.id), asset] } : {}) })); }} /><details className={styles.googleSettings}><summary>Descripción y encuadre</summary><div><label className={styles.field}>Descripción de imagen<textarea maxLength={250} value={photo.alt} onChange={event => edit({ alt: event.target.value })} /></label><label className={styles.field}>Posición<select value={photo.focal || "center"} onChange={event => edit({ focal: event.target.value as "left" | "center" | "right" })}><option value="left">Izquierda</option><option value="center">Centro</option><option value="right">Derecha</option></select></label></div></details><div className={styles.row}><button type="button" className={styles.secondary} disabled={!selected || uploadCount > 0} onClick={() => move(selected - 1)}><ArrowUp size={13} />Mover arriba</button><button type="button" className={styles.secondary} disabled={selected >= config.gallery.length - 1 || uploadCount > 0} onClick={() => move(selected + 1)}><ArrowDown size={13} />Mover abajo</button><button type="button" className={styles.secondary} disabled={uploadCount > 0} onClick={remove}><Trash2 size={13} />Retirar foto</button></div></div> : null}
    {config.gallery.length < 30 ? <MediaPicker label="Añadir foto a la galería" value="" usage="gallery" onBusy={busy} onLocalPreview={url => onLocal("galleryNew", url)} onFocus={() => highlight()} onChange={(url, asset) => { if (!url || !asset) return; setSelected(config.gallery.length); update(previous => ({ ...previous, gallery: [...previous.gallery, { image: url, name: "Nuevo trabajo", alt: "Nuevo trabajo", category: "", categoryIds: [] }], mediaAssets: [...(previous.mediaAssets ?? []).filter(entry => entry.id !== asset.id), asset] })); }} /> : <p className={styles.helper}>Tu galería tiene 30 fotos.</p>}
  </div>;
}
