"use client";
import { useState, useTransition } from "react";
import Link from "next/link";
import { initializePaddle } from "@paddle/paddle-js";
import { type BellaConfig } from "@/websites/config";
import { hasWebsiteEntitlement } from "@/websites/policy";
import { regularizeWebsiteAddon, uploadWebsiteImage, saveWebsiteDraft, publishWebsite, suspendWebsite, activateWebsiteAddon, cancelWebsiteAddon, reactivateWebsiteAddon, connectWebsiteDomain, checkWebsiteDomain, requestWebsiteDomain, setPrimaryWebsiteDomain } from "@/server/actions/website.actions";
type Props = { initial: BellaConfig; revision: number; subdomain: string; rootDomain: string; status: string; addon: { status: string; cancelAt: string | null; validUntil: string | null } | null; price: { id: string; amount: string; currency: string } | null; domains: { id: string; hostname: string; status: string; token: string; primary: boolean }[]; requests: { id: string; hostname: string; status: string }[] };
const inputClass = "w-full rounded-lg border border-border bg-background px-3 py-2 text-sm";
export default function WebsiteEditor(props: Props) {
  const [config, setConfig] = useState(props.initial), [revision, setRevision] = useState(props.revision), [subdomain, setSubdomain] = useState(props.subdomain);
  const [message, setMessage] = useState(""), [pending, start] = useTransition(), [hostname, setHostname] = useState(""), [requested, setRequested] = useState("");
  const [dirty, setDirty] = useState(false);
  const change = <K extends keyof BellaConfig>(key: K, value: BellaConfig[K]) => { setConfig(previous => ({ ...previous, [key]: value })); setDirty(true); };
  const run = (operation: () => Promise<unknown>, success = "Listo") => start(async () => { setMessage(""); try { const result = await operation(); if (result && typeof result === "object" && "error" in result) throw new Error(String(result.error)); setMessage(typeof result === "string" ? result : success); } catch (error) { setMessage(error instanceof Error ? error.message : "No pudimos guardar el cambio"); } });
  const csv = (value: string) => value.trim() ? value.split(",").map(item => item.trim()) : [];
  const mediaKeys = new Set(["logo", "favicon", "heroImage", "aboutImage", "socialImage"]);
  const upload = (file: File | undefined, apply: (url: string) => void) => { if (!file) return; run(async () => { const data = new FormData(); data.set("image", file); const result = await uploadWebsiteImage(data); if (typeof result !== "string") throw new Error(result.error); apply(result); }, "Imagen subida. Guarda el borrador para conservarla."); };
  const field = (key: keyof BellaConfig, label: string, multiline = false) => <div className="grid gap-2 text-sm" key={key}><label className="grid gap-2">{label}{multiline ? <textarea disabled={pending} aria-label={label} rows={4} className={inputClass} value={String(config[key])} onChange={event => change(key, event.target.value as never)} /> : <input disabled={pending} aria-label={label} className={inputClass} value={String(config[key])} onChange={event => change(key, event.target.value as never)} />}</label>{mediaKeys.has(key) ? <input type="file" accept="image/jpeg,image/png,image/webp" disabled={pending} aria-label={`Subir ${label}`} onChange={event => upload(event.target.files?.[0], url => change(key, url as never))} /> : null}</div>;
  const section = "space-y-5 rounded-2xl border border-border bg-card p-5 sm:p-7";
  const active = hasWebsiteEntitlement(props.addon);
  async function checkout(recover = false) {
    const token = process.env.NEXT_PUBLIC_PADDLE_CLIENT_TOKEN;
    if (!token?.startsWith("test")) throw new Error("Configura el token de checkout sandbox");
    const result = await (recover ? regularizeWebsiteAddon() : activateWebsiteAddon());
    if ("error" in result) throw new Error(result.error);
    const paddle = await initializePaddle({ environment: "sandbox", token });
    if (!paddle) throw new Error("No pudimos abrir el checkout");
    paddle.Checkout.open({ transactionId: result.transactionId });
  }
  return <div className="mx-auto max-w-5xl space-y-7 pb-12">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-muted-foreground">Puragenda · Sitio Web</p><h1 className="text-3xl font-bold">Mi sitio web</h1><p className="mt-2 text-muted-foreground">Tu marca, tus servicios y tu agenda en un sitio profesional.</p></div><Link href="/dashboard/website/preview" target="_blank" className="rounded-lg border px-4 py-2">Vista previa</Link></header>
    <section className={section}><h2 className="text-xl font-semibold">{active ? "Sitio Web activo" : "Tu negocio ya puede tener su propia web"}</h2><p>Bella incluye diseño, reservas integradas, alojamiento, subdominio y conexión de dominio propio.</p><p>{props.price ? `${new Intl.NumberFormat("es-CL", { style: "currency", currency: props.price.currency, maximumFractionDigits: props.price.currency === "CLP" ? 0 : 2 }).format(Number(props.price.amount) / (props.price.currency === "CLP" ? 1 : 100))} / mes · adicional al plan base` : "Catálogo sandbox pendiente de configuración. Precio comercial objetivo: $9.990 CLP / mes."}</p>{!active ? <button className="rounded-lg bg-primary px-4 py-2 text-primary-foreground" disabled={pending || (!props.price && props.addon?.status !== "PAST_DUE")} onClick={() => run(() => checkout(props.addon?.status === "PAST_DUE"), "Completa el checkout. La activación se confirma por webhook.")}>Activar Sitio Web · sandbox</button> : props.addon?.cancelAt ? <><p>Tu web seguirá activa hasta {new Date(props.addon.cancelAt).toLocaleDateString("es-CL")}. Después quedará suspendida; tu contenido se conserva.</p><button disabled={pending} onClick={() => run(() => reactivateWebsiteAddon(true), "Reactivación solicitada. Esperando confirmación de billing.")}>Reactivar add-on</button></> : <button disabled={pending} onClick={() => { if (window.confirm(`Cancelar solo Sitio Web en sandbox: seguirá activo hasta ${props.addon?.validUntil ? new Date(props.addon.validUntil).toLocaleDateString("es-CL") : "el fin del período"}. Conservaremos el contenido.`)) run(() => cancelWebsiteAddon(true), "Cancelación solicitada. Tu plan base continúa."); }}>Cancelar add-on al finalizar el período</button>}</section>
    <section className={section}><h2 className="text-xl font-semibold">Diseño · Bella</h2><p>Belleza · Uñas · Cejas · Pestañas · Estética. Tipografía editorial, fotografía y movimiento.</p><div className="flex flex-wrap gap-4"><Link href="/dashboard/website/preview?mode=demo" target="_blank" className="underline">Ver diseño demostrativo</Link><Link href="/dashboard/website/preview?viewport=mobile" target="_blank" className="underline">Preview móvil</Link><span>Diseño seleccionado: Bella · v1</span></div><label className="grid gap-2 text-sm">Paleta permitida<select disabled={pending} className={inputClass} value={config.accent} onChange={event => change("accent", event.target.value as BellaConfig["accent"])}><option value="coral">Coral</option><option value="plum">Ciruela</option><option value="forest">Bosque</option></select></label></section>
    <section className={section}><h2 className="text-xl font-semibold">Contenido y fotografías</h2><p className="text-sm text-muted-foreground">Sube tus fotos o pega una URL de Cloudinary. Los servicios, precios y profesionales se administran en Puragenda.</p><div className="grid gap-5 sm:grid-cols-2">{field("displayName", "Nombre mostrado (vacío usa el negocio)")}{field("brandEyebrow", "Primera línea de marca")}{field("brandTitle", "Marca protagonista")}{field("logo", "Logo · URL")}{field("favicon", "Favicon · URL")}{field("heroImage", "Foto de portada · URL")}{field("heroCaption", "Descripción de la fotografía")}{field("headline", "Titular (permite saltos de línea)", true)}{field("intro", "Introducción", true)}{field("about", "Nosotros", true)}{field("aboutImage", "Foto del estudio · URL")}</div></section>
    <section className={section}><h2 className="text-xl font-semibold">Galería</h2><label className="grid gap-2">Orden de filtros (separados por coma)<input disabled={pending} className={inputClass} value={config.galleryFilters.join(", ")} onChange={event => change("galleryFilters", csv(event.target.value))} /></label>{config.gallery.map((image, index) => <fieldset key={index} className="grid gap-3 border-t pt-4 sm:grid-cols-2"><legend>Imagen {index + 1}</legend>{(["image", "name", "alt", "category"] as const).map(key => <label key={key} className="grid gap-1 text-sm">{{ image: "URL", name: "Título", alt: "Texto alternativo", category: "Categoría" }[key]}<input disabled={pending} className={inputClass} value={image[key]} onChange={event => change("gallery", config.gallery.map((item, position) => position === index ? { ...item, [key]: event.target.value } : item))} /></label>)}<label>Filtros (separados por coma)<input disabled={pending} className={inputClass} value={(image.filters ?? [image.category]).join(", ")} onChange={event => change("gallery",config.gallery.map((item,position) => position === index ? {...item,filters:csv(event.target.value)} : item))} /></label><label>Encuadre<select disabled={pending} className={inputClass} value={image.focal ?? "center"} onChange={event=>change("gallery",config.gallery.map((item,position)=>position===index ? {...item,focal:event.target.value as "center" | "left" | "right"}:item))}><option value="center">Centro</option><option value="left">Izquierda</option><option value="right">Derecha</option></select></label><input type="file" aria-label={`Subir imagen ${index+1}`} accept="image/jpeg,image/png,image/webp" disabled={pending} onChange={event=>upload(event.target.files?.[0],url=>change("gallery",config.gallery.map((item,position)=>position===index ? {...item,image:url}:item)))} /><button disabled={pending} onClick={() => change("gallery", config.gallery.filter((_, position) => position !== index))}>Quitar imagen</button></fieldset>)}<button disabled={pending || config.gallery.length >= 30} onClick={() => change("gallery", [...config.gallery, { image: "", name: "", alt: "", category: "" }])}>Añadir imagen</button></section>
    <section className={section}><h2 className="text-xl font-semibold">Contacto y redes</h2><div className="grid gap-5 sm:grid-cols-2">{field("contactEmail", "Email")}{field("phone", "Teléfono")}{field("whatsapp", "WhatsApp · número internacional")}{field("instagram", "Instagram · URL https")}{field("facebook", "Facebook · URL https")}</div></section>
    <section className={section}><h2 className="text-xl font-semibold">SEO</h2>{field("seoTitle", "Título SEO")}{field("seoDescription", "Descripción SEO", true)}{field("socialImage", "Imagen social · URL")}</section>
    <section className={section}><h2 className="text-xl font-semibold">Dominio</h2><label className="grid gap-2">Subdominio<input disabled={pending} className={inputClass} value={subdomain} onChange={event => { setSubdomain(event.target.value.toLowerCase()); setDirty(true); }} /></label><p>{subdomain}.{props.rootDomain}</p><p className="text-sm text-muted-foreground">Los cambios de DNS y conexión SSL requieren configuración de infraestructura.</p><div className="flex flex-wrap gap-3"><input disabled={pending} aria-label="Dominio propio" placeholder="tumarca.cl" className={inputClass} value={hostname} onChange={event => setHostname(event.target.value)} /><button disabled={pending || !hostname} onClick={() => run(() => connectWebsiteDomain(hostname), "Dominio registrado. Publica el TXT y verifica.")}>Conectar dominio propio</button></div>{props.domains.map(domain => <div key={domain.id} className="break-all border-t pt-3"><p>{domain.hostname} · {domain.status}{domain.primary ? " · principal" : ""}</p><p className="text-sm">TXT en _puragenda.{domain.hostname}: <code>{domain.token}</code></p><button disabled={pending} onClick={() => run(() => checkWebsiteDomain(domain.id), "Verificación completada")}>Verificar propiedad</button>{domain.status === "ACTIVE" ? <button disabled={pending} onClick={() => run(() => setPrimaryWebsiteDomain(domain.id))}>Usar como principal</button> : null}</div>)}<div className="border-t pt-5"><h3 className="font-semibold">Solicitar compra de dominio</h3><input disabled={pending} aria-label="Dominio solicitado" className={inputClass} value={requested} placeholder="midominio.cl" onChange={event => setRequested(event.target.value)} /><p className="text-sm">Soporte revisará la disponibilidad y cotización. Esta solicitud no compra el dominio.</p><button disabled={pending || !requested} onClick={() => run(() => requestWebsiteDomain(requested, ""), "Solicitud recibida para revisión")}>Solicitar cotización</button>{props.requests.map(request => <p key={request.id}>{request.hostname} · {request.status}</p>)}</div></section>
    <section className={section}><h2 className="text-xl font-semibold">Publicación · {props.status}</h2><p>Guardar actualiza el borrador. Publicar reemplaza la configuración pública con ese borrador guardado.</p><div className="flex flex-wrap gap-4"><button disabled={pending} className="rounded-lg border px-4 py-2" onClick={() => run(async () => { const saved = await saveWebsiteDraft(config, revision, subdomain); if ("error" in saved) throw new Error(saved.error); setRevision(saved.revision); setDirty(false); }, "Borrador guardado")}>Guardar</button><Link href="/dashboard/website/preview" target="_blank" className="rounded-lg border px-4 py-2">Previsualizar borrador guardado</Link><button disabled={pending || dirty || !active} className="rounded-lg bg-primary px-4 py-2 text-primary-foreground" onClick={() => run(() => publishWebsite(revision), "Sitio publicado")}>Publicar cambios</button><button disabled={pending || props.status !== "PUBLISHED"} onClick={() => run(suspendWebsite, "Sitio despublicado. Contenido conservado.")}>Despublicar</button></div>{dirty ? <p>Hay cambios sin guardar.</p> : null}</section>
    <p role="status" className="sticky bottom-3 rounded-lg bg-background p-3 shadow">{pending ? "Procesando…" : message}</p>
  </div>;
}
