export type ChileCommune = {
  code: string;
  name: string;
  slug: string;
};

export type ChileRegion = {
  code: string;
  name: string;
  communes: readonly ChileCommune[];
};

/** Official 16-region / 346-commune catalog, verified against BCN and INE DPA. */
export const CHILE_REGIONS: readonly ChileRegion[] = [
  { code: "15", name: "Arica y Parinacota", communes: [
    { code: "15101", name: "Arica", slug: "arica" },
    { code: "15102", name: "Camarones", slug: "camarones" },
    { code: "15201", name: "Putre", slug: "putre" },
    { code: "15202", name: "General Lagos", slug: "general-lagos" },
  ] },
  { code: "01", name: "Tarapacá", communes: [
    { code: "01101", name: "Iquique", slug: "iquique" },
    { code: "01107", name: "Alto Hospicio", slug: "alto-hospicio" },
    { code: "01401", name: "Pozo Almonte", slug: "pozo-almonte" },
    { code: "01402", name: "Camiña", slug: "camina" },
    { code: "01403", name: "Colchane", slug: "colchane" },
    { code: "01404", name: "Huara", slug: "huara" },
    { code: "01405", name: "Pica", slug: "pica" },
  ] },
  { code: "02", name: "Antofagasta", communes: [
    { code: "02101", name: "Antofagasta", slug: "antofagasta" },
    { code: "02102", name: "Mejillones", slug: "mejillones" },
    { code: "02103", name: "Sierra Gorda", slug: "sierra-gorda" },
    { code: "02104", name: "Taltal", slug: "taltal" },
    { code: "02201", name: "Calama", slug: "calama" },
    { code: "02202", name: "Ollagüe", slug: "ollague" },
    { code: "02203", name: "San Pedro de Atacama", slug: "san-pedro-de-atacama" },
    { code: "02301", name: "Tocopilla", slug: "tocopilla" },
    { code: "02302", name: "María Elena", slug: "maria-elena" },
  ] },
  { code: "03", name: "Atacama", communes: [
    { code: "03101", name: "Copiapó", slug: "copiapo" },
    { code: "03102", name: "Caldera", slug: "caldera" },
    { code: "03103", name: "Tierra Amarilla", slug: "tierra-amarilla" },
    { code: "03201", name: "Chañaral", slug: "chanaral" },
    { code: "03202", name: "Diego de Almagro", slug: "diego-de-almagro" },
    { code: "03301", name: "Vallenar", slug: "vallenar" },
    { code: "03302", name: "Alto del Carmen", slug: "alto-del-carmen" },
    { code: "03303", name: "Freirina", slug: "freirina" },
    { code: "03304", name: "Huasco", slug: "huasco" },
  ] },
  { code: "04", name: "Coquimbo", communes: [
    { code: "04101", name: "La Serena", slug: "la-serena" },
    { code: "04102", name: "Coquimbo", slug: "coquimbo" },
    { code: "04103", name: "Andacollo", slug: "andacollo" },
    { code: "04104", name: "La Higuera", slug: "la-higuera" },
    { code: "04105", name: "Paihuano", slug: "paihuano" },
    { code: "04106", name: "Vicuña", slug: "vicuna" },
    { code: "04201", name: "Illapel", slug: "illapel" },
    { code: "04202", name: "Canela", slug: "canela" },
    { code: "04203", name: "Los Vilos", slug: "los-vilos" },
    { code: "04204", name: "Salamanca", slug: "salamanca" },
    { code: "04301", name: "Ovalle", slug: "ovalle" },
    { code: "04302", name: "Combarbalá", slug: "combarbala" },
    { code: "04303", name: "Monte Patria", slug: "monte-patria" },
    { code: "04304", name: "Punitaqui", slug: "punitaqui" },
    { code: "04305", name: "Río Hurtado", slug: "rio-hurtado" },
  ] },
  { code: "05", name: "Valparaíso", communes: [
    { code: "05101", name: "Valparaíso", slug: "valparaiso" },
    { code: "05102", name: "Casablanca", slug: "casablanca" },
    { code: "05103", name: "Concón", slug: "concon" },
    { code: "05104", name: "Juan Fernández", slug: "juan-fernandez" },
    { code: "05105", name: "Puchuncaví", slug: "puchuncavi" },
    { code: "05107", name: "Quintero", slug: "quintero" },
    { code: "05109", name: "Viña del Mar", slug: "vina-del-mar" },
    { code: "05201", name: "Isla de Pascua", slug: "isla-de-pascua" },
    { code: "05301", name: "Los Andes", slug: "los-andes" },
    { code: "05302", name: "Calle Larga", slug: "calle-larga" },
    { code: "05303", name: "Rinconada", slug: "rinconada" },
    { code: "05304", name: "San Esteban", slug: "san-esteban" },
    { code: "05401", name: "La Ligua", slug: "la-ligua" },
    { code: "05402", name: "Cabildo", slug: "cabildo" },
    { code: "05403", name: "Papudo", slug: "papudo" },
    { code: "05404", name: "Petorca", slug: "petorca" },
    { code: "05405", name: "Zapallar", slug: "zapallar" },
    { code: "05501", name: "Quillota", slug: "quillota" },
    { code: "05502", name: "La Calera", slug: "la-calera" },
    { code: "05503", name: "Hijuelas", slug: "hijuelas" },
    { code: "05504", name: "La Cruz", slug: "la-cruz" },
    { code: "05506", name: "Nogales", slug: "nogales" },
    { code: "05601", name: "San Antonio", slug: "san-antonio" },
    { code: "05602", name: "Algarrobo", slug: "algarrobo" },
    { code: "05603", name: "Cartagena", slug: "cartagena" },
    { code: "05604", name: "El Quisco", slug: "el-quisco" },
    { code: "05605", name: "El Tabo", slug: "el-tabo" },
    { code: "05606", name: "Santo Domingo", slug: "santo-domingo" },
    { code: "05701", name: "San Felipe", slug: "san-felipe" },
    { code: "05702", name: "Catemu", slug: "catemu" },
    { code: "05703", name: "Llaillay", slug: "llaillay" },
    { code: "05704", name: "Panquehue", slug: "panquehue" },
    { code: "05705", name: "Putaendo", slug: "putaendo" },
    { code: "05706", name: "Santa María", slug: "santa-maria" },
    { code: "05801", name: "Quilpué", slug: "quilpue" },
    { code: "05802", name: "Limache", slug: "limache" },
    { code: "05803", name: "Olmué", slug: "olmue" },
    { code: "05804", name: "Villa Alemana", slug: "villa-alemana" },
  ] },
  { code: "13", name: "Metropolitana de Santiago", communes: [
    { code: "13101", name: "Santiago", slug: "santiago" },
    { code: "13102", name: "Cerrillos", slug: "cerrillos" },
    { code: "13103", name: "Cerro Navia", slug: "cerro-navia" },
    { code: "13104", name: "Conchalí", slug: "conchali" },
    { code: "13105", name: "El Bosque", slug: "el-bosque" },
    { code: "13106", name: "Estación Central", slug: "estacion-central" },
    { code: "13107", name: "Huechuraba", slug: "huechuraba" },
    { code: "13108", name: "Independencia", slug: "independencia" },
    { code: "13109", name: "La Cisterna", slug: "la-cisterna" },
    { code: "13110", name: "La Florida", slug: "la-florida" },
    { code: "13111", name: "La Granja", slug: "la-granja" },
    { code: "13112", name: "La Pintana", slug: "la-pintana" },
    { code: "13113", name: "La Reina", slug: "la-reina" },
    { code: "13114", name: "Las Condes", slug: "las-condes" },
    { code: "13115", name: "Lo Barnechea", slug: "lo-barnechea" },
    { code: "13116", name: "Lo Espejo", slug: "lo-espejo" },
    { code: "13117", name: "Lo Prado", slug: "lo-prado" },
    { code: "13118", name: "Macul", slug: "macul" },
    { code: "13119", name: "Maipú", slug: "maipu" },
    { code: "13120", name: "Ñuñoa", slug: "nunoa" },
    { code: "13121", name: "Pedro Aguirre Cerda", slug: "pedro-aguirre-cerda" },
    { code: "13122", name: "Peñalolén", slug: "penalolen" },
    { code: "13123", name: "Providencia", slug: "providencia" },
    { code: "13124", name: "Pudahuel", slug: "pudahuel" },
    { code: "13125", name: "Quilicura", slug: "quilicura" },
    { code: "13126", name: "Quinta Normal", slug: "quinta-normal" },
    { code: "13127", name: "Recoleta", slug: "recoleta" },
    { code: "13128", name: "Renca", slug: "renca" },
    { code: "13129", name: "San Joaquín", slug: "san-joaquin" },
    { code: "13130", name: "San Miguel", slug: "san-miguel" },
    { code: "13131", name: "San Ramón", slug: "san-ramon" },
    { code: "13132", name: "Vitacura", slug: "vitacura" },
    { code: "13201", name: "Puente Alto", slug: "puente-alto" },
    { code: "13202", name: "Pirque", slug: "pirque" },
    { code: "13203", name: "San José de Maipo", slug: "san-jose-de-maipo" },
    { code: "13301", name: "Colina", slug: "colina" },
    { code: "13302", name: "Lampa", slug: "lampa" },
    { code: "13303", name: "Tiltil", slug: "tiltil" },
    { code: "13401", name: "San Bernardo", slug: "san-bernardo" },
    { code: "13402", name: "Buin", slug: "buin" },
    { code: "13403", name: "Calera de Tango", slug: "calera-de-tango" },
    { code: "13404", name: "Paine", slug: "paine" },
    { code: "13501", name: "Melipilla", slug: "melipilla" },
    { code: "13502", name: "Alhué", slug: "alhue" },
    { code: "13503", name: "Curacaví", slug: "curacavi" },
    { code: "13504", name: "María Pinto", slug: "maria-pinto" },
    { code: "13505", name: "San Pedro", slug: "san-pedro" },
    { code: "13601", name: "Talagante", slug: "talagante" },
    { code: "13602", name: "El Monte", slug: "el-monte" },
    { code: "13603", name: "Isla de Maipo", slug: "isla-de-maipo" },
    { code: "13604", name: "Padre Hurtado", slug: "padre-hurtado" },
    { code: "13605", name: "Peñaflor", slug: "penaflor" },
  ] },
  { code: "06", name: "Libertador General Bernardo O'Higgins", communes: [
    { code: "06101", name: "Rancagua", slug: "rancagua" },
    { code: "06102", name: "Codegua", slug: "codegua" },
    { code: "06103", name: "Coinco", slug: "coinco" },
    { code: "06104", name: "Coltauco", slug: "coltauco" },
    { code: "06105", name: "Doñihue", slug: "donihue" },
    { code: "06106", name: "Graneros", slug: "graneros" },
    { code: "06107", name: "Las Cabras", slug: "las-cabras" },
    { code: "06108", name: "Machalí", slug: "machali" },
    { code: "06109", name: "Malloa", slug: "malloa" },
    { code: "06110", name: "Mostazal", slug: "mostazal" },
    { code: "06111", name: "Olivar", slug: "olivar" },
    { code: "06112", name: "Peumo", slug: "peumo" },
    { code: "06113", name: "Pichidegua", slug: "pichidegua" },
    { code: "06114", name: "Quinta de Tilcoco", slug: "quinta-de-tilcoco" },
    { code: "06115", name: "Rengo", slug: "rengo" },
    { code: "06116", name: "Requínoa", slug: "requinoa" },
    { code: "06117", name: "San Vicente", slug: "san-vicente" },
    { code: "06201", name: "Pichilemu", slug: "pichilemu" },
    { code: "06202", name: "La Estrella", slug: "la-estrella" },
    { code: "06203", name: "Litueche", slug: "litueche" },
    { code: "06204", name: "Marchihue", slug: "marchihue" },
    { code: "06205", name: "Navidad", slug: "navidad" },
    { code: "06206", name: "Paredones", slug: "paredones" },
    { code: "06301", name: "San Fernando", slug: "san-fernando" },
    { code: "06302", name: "Chépica", slug: "chepica" },
    { code: "06303", name: "Chimbarongo", slug: "chimbarongo" },
    { code: "06304", name: "Lolol", slug: "lolol" },
    { code: "06305", name: "Nancagua", slug: "nancagua" },
    { code: "06306", name: "Palmilla", slug: "palmilla" },
    { code: "06307", name: "Peralillo", slug: "peralillo" },
    { code: "06308", name: "Placilla", slug: "placilla" },
    { code: "06309", name: "Pumanque", slug: "pumanque" },
    { code: "06310", name: "Santa Cruz", slug: "santa-cruz" },
  ] },
  { code: "07", name: "Maule", communes: [
    { code: "07101", name: "Talca", slug: "talca" },
    { code: "07102", name: "Constitución", slug: "constitucion" },
    { code: "07103", name: "Curepto", slug: "curepto" },
    { code: "07104", name: "Empedrado", slug: "empedrado" },
    { code: "07105", name: "Maule", slug: "maule" },
    { code: "07106", name: "Pelarco", slug: "pelarco" },
    { code: "07107", name: "Pencahue", slug: "pencahue" },
    { code: "07108", name: "Río Claro", slug: "rio-claro" },
    { code: "07109", name: "San Clemente", slug: "san-clemente" },
    { code: "07110", name: "San Rafael", slug: "san-rafael" },
    { code: "07201", name: "Cauquenes", slug: "cauquenes" },
    { code: "07202", name: "Chanco", slug: "chanco" },
    { code: "07203", name: "Pelluhue", slug: "pelluhue" },
    { code: "07301", name: "Curicó", slug: "curico" },
    { code: "07302", name: "Hualañé", slug: "hualane" },
    { code: "07303", name: "Licantén", slug: "licanten" },
    { code: "07304", name: "Molina", slug: "molina" },
    { code: "07305", name: "Rauco", slug: "rauco" },
    { code: "07306", name: "Romeral", slug: "romeral" },
    { code: "07307", name: "Sagrada Familia", slug: "sagrada-familia" },
    { code: "07308", name: "Teno", slug: "teno" },
    { code: "07309", name: "Vichuquén", slug: "vichuquen" },
    { code: "07401", name: "Linares", slug: "linares" },
    { code: "07402", name: "Colbún", slug: "colbun" },
    { code: "07403", name: "Longaví", slug: "longavi" },
    { code: "07404", name: "Parral", slug: "parral" },
    { code: "07405", name: "Retiro", slug: "retiro" },
    { code: "07406", name: "San Javier", slug: "san-javier" },
    { code: "07407", name: "Villa Alegre", slug: "villa-alegre" },
    { code: "07408", name: "Yerbas Buenas", slug: "yerbas-buenas" },
  ] },
  { code: "16", name: "Ñuble", communes: [
    { code: "16101", name: "Chillán", slug: "chillan" },
    { code: "16102", name: "Bulnes", slug: "bulnes" },
    { code: "16103", name: "Chillán Viejo", slug: "chillan-viejo" },
    { code: "16104", name: "El Carmen", slug: "el-carmen" },
    { code: "16105", name: "Pemuco", slug: "pemuco" },
    { code: "16106", name: "Pinto", slug: "pinto" },
    { code: "16107", name: "Quillón", slug: "quillon" },
    { code: "16108", name: "San Ignacio", slug: "san-ignacio" },
    { code: "16109", name: "Yungay", slug: "yungay" },
    { code: "16201", name: "Quirihue", slug: "quirihue" },
    { code: "16202", name: "Cobquecura", slug: "cobquecura" },
    { code: "16203", name: "Coelemu", slug: "coelemu" },
    { code: "16204", name: "Ninhue", slug: "ninhue" },
    { code: "16205", name: "Portezuelo", slug: "portezuelo" },
    { code: "16206", name: "Ránquil", slug: "ranquil" },
    { code: "16207", name: "Treguaco", slug: "treguaco" },
    { code: "16301", name: "San Carlos", slug: "san-carlos" },
    { code: "16302", name: "Coihueco", slug: "coihueco" },
    { code: "16303", name: "Ñiquén", slug: "niquen" },
    { code: "16304", name: "San Fabián", slug: "san-fabian" },
    { code: "16305", name: "San Nicolás", slug: "san-nicolas" },
  ] },
  { code: "08", name: "Biobío", communes: [
    { code: "08101", name: "Concepción", slug: "concepcion" },
    { code: "08102", name: "Coronel", slug: "coronel" },
    { code: "08103", name: "Chiguayante", slug: "chiguayante" },
    { code: "08104", name: "Florida", slug: "florida" },
    { code: "08105", name: "Hualqui", slug: "hualqui" },
    { code: "08106", name: "Lota", slug: "lota" },
    { code: "08107", name: "Penco", slug: "penco" },
    { code: "08108", name: "San Pedro de la Paz", slug: "san-pedro-de-la-paz" },
    { code: "08109", name: "Santa Juana", slug: "santa-juana" },
    { code: "08110", name: "Talcahuano", slug: "talcahuano" },
    { code: "08111", name: "Tomé", slug: "tome" },
    { code: "08112", name: "Hualpén", slug: "hualpen" },
    { code: "08201", name: "Lebu", slug: "lebu" },
    { code: "08202", name: "Arauco", slug: "arauco" },
    { code: "08203", name: "Cañete", slug: "canete" },
    { code: "08204", name: "Contulmo", slug: "contulmo" },
    { code: "08205", name: "Curanilahue", slug: "curanilahue" },
    { code: "08206", name: "Los Álamos", slug: "los-alamos" },
    { code: "08207", name: "Tirúa", slug: "tirua" },
    { code: "08301", name: "Los Ángeles", slug: "los-angeles" },
    { code: "08302", name: "Antuco", slug: "antuco" },
    { code: "08303", name: "Cabrero", slug: "cabrero" },
    { code: "08304", name: "Laja", slug: "laja" },
    { code: "08305", name: "Mulchén", slug: "mulchen" },
    { code: "08306", name: "Nacimiento", slug: "nacimiento" },
    { code: "08307", name: "Negrete", slug: "negrete" },
    { code: "08308", name: "Quilaco", slug: "quilaco" },
    { code: "08309", name: "Quilleco", slug: "quilleco" },
    { code: "08310", name: "San Rosendo", slug: "san-rosendo" },
    { code: "08311", name: "Santa Bárbara", slug: "santa-barbara" },
    { code: "08312", name: "Tucapel", slug: "tucapel" },
    { code: "08313", name: "Yumbel", slug: "yumbel" },
    { code: "08314", name: "Alto Biobío", slug: "alto-biobio" },
  ] },
  { code: "09", name: "La Araucanía", communes: [
    { code: "09101", name: "Temuco", slug: "temuco" },
    { code: "09102", name: "Carahue", slug: "carahue" },
    { code: "09103", name: "Cunco", slug: "cunco" },
    { code: "09104", name: "Curarrehue", slug: "curarrehue" },
    { code: "09105", name: "Freire", slug: "freire" },
    { code: "09106", name: "Galvarino", slug: "galvarino" },
    { code: "09107", name: "Gorbea", slug: "gorbea" },
    { code: "09108", name: "Lautaro", slug: "lautaro" },
    { code: "09109", name: "Loncoche", slug: "loncoche" },
    { code: "09110", name: "Melipeuco", slug: "melipeuco" },
    { code: "09111", name: "Nueva Imperial", slug: "nueva-imperial" },
    { code: "09112", name: "Padre Las Casas", slug: "padre-las-casas" },
    { code: "09113", name: "Perquenco", slug: "perquenco" },
    { code: "09114", name: "Pitrufquén", slug: "pitrufquen" },
    { code: "09115", name: "Pucón", slug: "pucon" },
    { code: "09116", name: "Saavedra", slug: "saavedra" },
    { code: "09117", name: "Teodoro Schmidt", slug: "teodoro-schmidt" },
    { code: "09118", name: "Toltén", slug: "tolten" },
    { code: "09119", name: "Vilcún", slug: "vilcun" },
    { code: "09120", name: "Villarrica", slug: "villarrica" },
    { code: "09121", name: "Cholchol", slug: "cholchol" },
    { code: "09201", name: "Angol", slug: "angol" },
    { code: "09202", name: "Collipulli", slug: "collipulli" },
    { code: "09203", name: "Curacautín", slug: "curacautin" },
    { code: "09204", name: "Ercilla", slug: "ercilla" },
    { code: "09205", name: "Lonquimay", slug: "lonquimay" },
    { code: "09206", name: "Los Sauces", slug: "los-sauces" },
    { code: "09207", name: "Lumaco", slug: "lumaco" },
    { code: "09208", name: "Purén", slug: "puren" },
    { code: "09209", name: "Renaico", slug: "renaico" },
    { code: "09210", name: "Traiguén", slug: "traiguen" },
    { code: "09211", name: "Victoria", slug: "victoria" },
  ] },
  { code: "14", name: "Los Ríos", communes: [
    { code: "14101", name: "Valdivia", slug: "valdivia" },
    { code: "14102", name: "Corral", slug: "corral" },
    { code: "14103", name: "Lanco", slug: "lanco" },
    { code: "14104", name: "Los Lagos", slug: "los-lagos" },
    { code: "14105", name: "Máfil", slug: "mafil" },
    { code: "14106", name: "Mariquina", slug: "mariquina" },
    { code: "14107", name: "Paillaco", slug: "paillaco" },
    { code: "14108", name: "Panguipulli", slug: "panguipulli" },
    { code: "14201", name: "La Unión", slug: "la-union" },
    { code: "14202", name: "Futrono", slug: "futrono" },
    { code: "14203", name: "Lago Ranco", slug: "lago-ranco" },
    { code: "14204", name: "Río Bueno", slug: "rio-bueno" },
  ] },
  { code: "10", name: "Los Lagos", communes: [
    { code: "10101", name: "Puerto Montt", slug: "puerto-montt" },
    { code: "10102", name: "Calbuco", slug: "calbuco" },
    { code: "10103", name: "Cochamó", slug: "cochamo" },
    { code: "10104", name: "Fresia", slug: "fresia" },
    { code: "10105", name: "Frutillar", slug: "frutillar" },
    { code: "10106", name: "Los Muermos", slug: "los-muermos" },
    { code: "10107", name: "Llanquihue", slug: "llanquihue" },
    { code: "10108", name: "Maullín", slug: "maullin" },
    { code: "10109", name: "Puerto Varas", slug: "puerto-varas" },
    { code: "10201", name: "Castro", slug: "castro" },
    { code: "10202", name: "Ancud", slug: "ancud" },
    { code: "10203", name: "Chonchi", slug: "chonchi" },
    { code: "10204", name: "Curaco de Vélez", slug: "curaco-de-velez" },
    { code: "10205", name: "Dalcahue", slug: "dalcahue" },
    { code: "10206", name: "Puqueldón", slug: "puqueldon" },
    { code: "10207", name: "Queilén", slug: "queilen" },
    { code: "10208", name: "Quellón", slug: "quellon" },
    { code: "10209", name: "Quemchi", slug: "quemchi" },
    { code: "10210", name: "Quinchao", slug: "quinchao" },
    { code: "10301", name: "Osorno", slug: "osorno" },
    { code: "10302", name: "Puerto Octay", slug: "puerto-octay" },
    { code: "10303", name: "Purranque", slug: "purranque" },
    { code: "10304", name: "Puyehue", slug: "puyehue" },
    { code: "10305", name: "Río Negro", slug: "rio-negro" },
    { code: "10306", name: "San Juan de la Costa", slug: "san-juan-de-la-costa" },
    { code: "10307", name: "San Pablo", slug: "san-pablo" },
    { code: "10401", name: "Chaitén", slug: "chaiten" },
    { code: "10402", name: "Futaleufú", slug: "futaleufu" },
    { code: "10403", name: "Hualaihué", slug: "hualaihue" },
    { code: "10404", name: "Palena", slug: "palena" },
  ] },
  { code: "11", name: "Aysén del General Carlos Ibáñez del Campo", communes: [
    { code: "11101", name: "Coyhaique", slug: "coyhaique" },
    { code: "11102", name: "Lago Verde", slug: "lago-verde" },
    { code: "11201", name: "Aysén", slug: "aysen" },
    { code: "11202", name: "Cisnes", slug: "cisnes" },
    { code: "11203", name: "Guaitecas", slug: "guaitecas" },
    { code: "11301", name: "Cochrane", slug: "cochrane" },
    { code: "11302", name: "O'Higgins", slug: "o-higgins" },
    { code: "11303", name: "Tortel", slug: "tortel" },
    { code: "11401", name: "Chile Chico", slug: "chile-chico" },
    { code: "11402", name: "Río Ibáñez", slug: "rio-ibanez" },
  ] },
  { code: "12", name: "Magallanes y de la Antártica Chilena", communes: [
    { code: "12101", name: "Punta Arenas", slug: "punta-arenas" },
    { code: "12102", name: "Laguna Blanca", slug: "laguna-blanca" },
    { code: "12103", name: "Río Verde", slug: "rio-verde" },
    { code: "12104", name: "San Gregorio", slug: "san-gregorio" },
    { code: "12201", name: "Cabo de Hornos", slug: "cabo-de-hornos" },
    { code: "12202", name: "Antártica", slug: "antartica" },
    { code: "12301", name: "Porvenir", slug: "porvenir" },
    { code: "12302", name: "Primavera", slug: "primavera" },
    { code: "12303", name: "Timaukel", slug: "timaukel" },
    { code: "12401", name: "Natales", slug: "natales" },
    { code: "12402", name: "Torres del Paine", slug: "torres-del-paine" },
  ] },
];

export const CHILE_COMMUNES = CHILE_REGIONS.flatMap((region) =>
  region.communes.map((commune) => ({ ...commune, regionName: region.name })),
);

export const CHILE_REGION_COUNT = 16;
export const CHILE_COMMUNE_COUNT = 346;
