-- Complete Chilean commune catalog for dashboard and registration selectors.
-- Source: Biblioteca del Congreso Nacional (SIIT) / INE DPA: 16 regions, 346 communes.
-- Idempotent: existing curated slugs keep their IDs and receive canonical labels/order.

INSERT INTO "MarketplaceLocality"
  ("id", "slug", "name", "regionName", "communeName", "isActive", "position", "createdAt", "updatedAt")
VALUES
  ('mloc_cl_15101', 'arica', 'Arica', 'Arica y Parinacota', 'Arica', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_15102', 'camarones', 'Camarones', 'Arica y Parinacota', 'Camarones', true, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_15201', 'putre', 'Putre', 'Arica y Parinacota', 'Putre', true, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_15202', 'general-lagos', 'General Lagos', 'Arica y Parinacota', 'General Lagos', true, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_01101', 'iquique', 'Iquique', 'Tarapacá', 'Iquique', true, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_01107', 'alto-hospicio', 'Alto Hospicio', 'Tarapacá', 'Alto Hospicio', true, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_01401', 'pozo-almonte', 'Pozo Almonte', 'Tarapacá', 'Pozo Almonte', true, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_01402', 'camina', 'Camiña', 'Tarapacá', 'Camiña', true, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_01403', 'colchane', 'Colchane', 'Tarapacá', 'Colchane', true, 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_01404', 'huara', 'Huara', 'Tarapacá', 'Huara', true, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_01405', 'pica', 'Pica', 'Tarapacá', 'Pica', true, 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_02101', 'antofagasta', 'Antofagasta', 'Antofagasta', 'Antofagasta', true, 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_02102', 'mejillones', 'Mejillones', 'Antofagasta', 'Mejillones', true, 13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_02103', 'sierra-gorda', 'Sierra Gorda', 'Antofagasta', 'Sierra Gorda', true, 14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_02104', 'taltal', 'Taltal', 'Antofagasta', 'Taltal', true, 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_02201', 'calama', 'Calama', 'Antofagasta', 'Calama', true, 16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_02202', 'ollague', 'Ollagüe', 'Antofagasta', 'Ollagüe', true, 17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_02203', 'san-pedro-de-atacama', 'San Pedro de Atacama', 'Antofagasta', 'San Pedro de Atacama', true, 18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_02301', 'tocopilla', 'Tocopilla', 'Antofagasta', 'Tocopilla', true, 19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_02302', 'maria-elena', 'María Elena', 'Antofagasta', 'María Elena', true, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_03101', 'copiapo', 'Copiapó', 'Atacama', 'Copiapó', true, 21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_03102', 'caldera', 'Caldera', 'Atacama', 'Caldera', true, 22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_03103', 'tierra-amarilla', 'Tierra Amarilla', 'Atacama', 'Tierra Amarilla', true, 23, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_03201', 'chanaral', 'Chañaral', 'Atacama', 'Chañaral', true, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_03202', 'diego-de-almagro', 'Diego de Almagro', 'Atacama', 'Diego de Almagro', true, 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_03301', 'vallenar', 'Vallenar', 'Atacama', 'Vallenar', true, 26, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_03302', 'alto-del-carmen', 'Alto del Carmen', 'Atacama', 'Alto del Carmen', true, 27, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_03303', 'freirina', 'Freirina', 'Atacama', 'Freirina', true, 28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_03304', 'huasco', 'Huasco', 'Atacama', 'Huasco', true, 29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_04101', 'la-serena', 'La Serena', 'Coquimbo', 'La Serena', true, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_04102', 'coquimbo', 'Coquimbo', 'Coquimbo', 'Coquimbo', true, 31, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_04103', 'andacollo', 'Andacollo', 'Coquimbo', 'Andacollo', true, 32, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_04104', 'la-higuera', 'La Higuera', 'Coquimbo', 'La Higuera', true, 33, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_04105', 'paihuano', 'Paihuano', 'Coquimbo', 'Paihuano', true, 34, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_04106', 'vicuna', 'Vicuña', 'Coquimbo', 'Vicuña', true, 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_04201', 'illapel', 'Illapel', 'Coquimbo', 'Illapel', true, 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_04202', 'canela', 'Canela', 'Coquimbo', 'Canela', true, 37, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_04203', 'los-vilos', 'Los Vilos', 'Coquimbo', 'Los Vilos', true, 38, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_04204', 'salamanca', 'Salamanca', 'Coquimbo', 'Salamanca', true, 39, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_04301', 'ovalle', 'Ovalle', 'Coquimbo', 'Ovalle', true, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_04302', 'combarbala', 'Combarbalá', 'Coquimbo', 'Combarbalá', true, 41, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_04303', 'monte-patria', 'Monte Patria', 'Coquimbo', 'Monte Patria', true, 42, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_04304', 'punitaqui', 'Punitaqui', 'Coquimbo', 'Punitaqui', true, 43, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_04305', 'rio-hurtado', 'Río Hurtado', 'Coquimbo', 'Río Hurtado', true, 44, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05101', 'valparaiso', 'Valparaíso', 'Valparaíso', 'Valparaíso', true, 45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05102', 'casablanca', 'Casablanca', 'Valparaíso', 'Casablanca', true, 46, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05103', 'concon', 'Concón', 'Valparaíso', 'Concón', true, 47, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05104', 'juan-fernandez', 'Juan Fernández', 'Valparaíso', 'Juan Fernández', true, 48, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05105', 'puchuncavi', 'Puchuncaví', 'Valparaíso', 'Puchuncaví', true, 49, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05107', 'quintero', 'Quintero', 'Valparaíso', 'Quintero', true, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05109', 'vina-del-mar', 'Viña del Mar', 'Valparaíso', 'Viña del Mar', true, 51, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05201', 'isla-de-pascua', 'Isla de Pascua', 'Valparaíso', 'Isla de Pascua', true, 52, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05301', 'los-andes', 'Los Andes', 'Valparaíso', 'Los Andes', true, 53, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05302', 'calle-larga', 'Calle Larga', 'Valparaíso', 'Calle Larga', true, 54, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05303', 'rinconada', 'Rinconada', 'Valparaíso', 'Rinconada', true, 55, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05304', 'san-esteban', 'San Esteban', 'Valparaíso', 'San Esteban', true, 56, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05401', 'la-ligua', 'La Ligua', 'Valparaíso', 'La Ligua', true, 57, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05402', 'cabildo', 'Cabildo', 'Valparaíso', 'Cabildo', true, 58, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05403', 'papudo', 'Papudo', 'Valparaíso', 'Papudo', true, 59, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05404', 'petorca', 'Petorca', 'Valparaíso', 'Petorca', true, 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05405', 'zapallar', 'Zapallar', 'Valparaíso', 'Zapallar', true, 61, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05501', 'quillota', 'Quillota', 'Valparaíso', 'Quillota', true, 62, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05502', 'la-calera', 'La Calera', 'Valparaíso', 'La Calera', true, 63, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05503', 'hijuelas', 'Hijuelas', 'Valparaíso', 'Hijuelas', true, 64, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05504', 'la-cruz', 'La Cruz', 'Valparaíso', 'La Cruz', true, 65, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05506', 'nogales', 'Nogales', 'Valparaíso', 'Nogales', true, 66, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05601', 'san-antonio', 'San Antonio', 'Valparaíso', 'San Antonio', true, 67, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05602', 'algarrobo', 'Algarrobo', 'Valparaíso', 'Algarrobo', true, 68, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05603', 'cartagena', 'Cartagena', 'Valparaíso', 'Cartagena', true, 69, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05604', 'el-quisco', 'El Quisco', 'Valparaíso', 'El Quisco', true, 70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05605', 'el-tabo', 'El Tabo', 'Valparaíso', 'El Tabo', true, 71, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05606', 'santo-domingo', 'Santo Domingo', 'Valparaíso', 'Santo Domingo', true, 72, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05701', 'san-felipe', 'San Felipe', 'Valparaíso', 'San Felipe', true, 73, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05702', 'catemu', 'Catemu', 'Valparaíso', 'Catemu', true, 74, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05703', 'llaillay', 'Llaillay', 'Valparaíso', 'Llaillay', true, 75, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05704', 'panquehue', 'Panquehue', 'Valparaíso', 'Panquehue', true, 76, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05705', 'putaendo', 'Putaendo', 'Valparaíso', 'Putaendo', true, 77, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05706', 'santa-maria', 'Santa María', 'Valparaíso', 'Santa María', true, 78, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05801', 'quilpue', 'Quilpué', 'Valparaíso', 'Quilpué', true, 79, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05802', 'limache', 'Limache', 'Valparaíso', 'Limache', true, 80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05803', 'olmue', 'Olmué', 'Valparaíso', 'Olmué', true, 81, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_05804', 'villa-alemana', 'Villa Alemana', 'Valparaíso', 'Villa Alemana', true, 82, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13101', 'santiago', 'Santiago', 'Metropolitana de Santiago', 'Santiago', true, 83, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13102', 'cerrillos', 'Cerrillos', 'Metropolitana de Santiago', 'Cerrillos', true, 84, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13103', 'cerro-navia', 'Cerro Navia', 'Metropolitana de Santiago', 'Cerro Navia', true, 85, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13104', 'conchali', 'Conchalí', 'Metropolitana de Santiago', 'Conchalí', true, 86, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13105', 'el-bosque', 'El Bosque', 'Metropolitana de Santiago', 'El Bosque', true, 87, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13106', 'estacion-central', 'Estación Central', 'Metropolitana de Santiago', 'Estación Central', true, 88, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13107', 'huechuraba', 'Huechuraba', 'Metropolitana de Santiago', 'Huechuraba', true, 89, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13108', 'independencia', 'Independencia', 'Metropolitana de Santiago', 'Independencia', true, 90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13109', 'la-cisterna', 'La Cisterna', 'Metropolitana de Santiago', 'La Cisterna', true, 91, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13110', 'la-florida', 'La Florida', 'Metropolitana de Santiago', 'La Florida', true, 92, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13111', 'la-granja', 'La Granja', 'Metropolitana de Santiago', 'La Granja', true, 93, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13112', 'la-pintana', 'La Pintana', 'Metropolitana de Santiago', 'La Pintana', true, 94, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13113', 'la-reina', 'La Reina', 'Metropolitana de Santiago', 'La Reina', true, 95, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13114', 'las-condes', 'Las Condes', 'Metropolitana de Santiago', 'Las Condes', true, 96, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13115', 'lo-barnechea', 'Lo Barnechea', 'Metropolitana de Santiago', 'Lo Barnechea', true, 97, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13116', 'lo-espejo', 'Lo Espejo', 'Metropolitana de Santiago', 'Lo Espejo', true, 98, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13117', 'lo-prado', 'Lo Prado', 'Metropolitana de Santiago', 'Lo Prado', true, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13118', 'macul', 'Macul', 'Metropolitana de Santiago', 'Macul', true, 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13119', 'maipu', 'Maipú', 'Metropolitana de Santiago', 'Maipú', true, 101, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13120', 'nunoa', 'Ñuñoa', 'Metropolitana de Santiago', 'Ñuñoa', true, 102, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13121', 'pedro-aguirre-cerda', 'Pedro Aguirre Cerda', 'Metropolitana de Santiago', 'Pedro Aguirre Cerda', true, 103, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13122', 'penalolen', 'Peñalolén', 'Metropolitana de Santiago', 'Peñalolén', true, 104, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13123', 'providencia', 'Providencia', 'Metropolitana de Santiago', 'Providencia', true, 105, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13124', 'pudahuel', 'Pudahuel', 'Metropolitana de Santiago', 'Pudahuel', true, 106, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13125', 'quilicura', 'Quilicura', 'Metropolitana de Santiago', 'Quilicura', true, 107, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13126', 'quinta-normal', 'Quinta Normal', 'Metropolitana de Santiago', 'Quinta Normal', true, 108, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13127', 'recoleta', 'Recoleta', 'Metropolitana de Santiago', 'Recoleta', true, 109, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13128', 'renca', 'Renca', 'Metropolitana de Santiago', 'Renca', true, 110, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13129', 'san-joaquin', 'San Joaquín', 'Metropolitana de Santiago', 'San Joaquín', true, 111, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13130', 'san-miguel', 'San Miguel', 'Metropolitana de Santiago', 'San Miguel', true, 112, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13131', 'san-ramon', 'San Ramón', 'Metropolitana de Santiago', 'San Ramón', true, 113, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13132', 'vitacura', 'Vitacura', 'Metropolitana de Santiago', 'Vitacura', true, 114, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13201', 'puente-alto', 'Puente Alto', 'Metropolitana de Santiago', 'Puente Alto', true, 115, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13202', 'pirque', 'Pirque', 'Metropolitana de Santiago', 'Pirque', true, 116, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13203', 'san-jose-de-maipo', 'San José de Maipo', 'Metropolitana de Santiago', 'San José de Maipo', true, 117, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13301', 'colina', 'Colina', 'Metropolitana de Santiago', 'Colina', true, 118, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13302', 'lampa', 'Lampa', 'Metropolitana de Santiago', 'Lampa', true, 119, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13303', 'tiltil', 'Tiltil', 'Metropolitana de Santiago', 'Tiltil', true, 120, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13401', 'san-bernardo', 'San Bernardo', 'Metropolitana de Santiago', 'San Bernardo', true, 121, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13402', 'buin', 'Buin', 'Metropolitana de Santiago', 'Buin', true, 122, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13403', 'calera-de-tango', 'Calera de Tango', 'Metropolitana de Santiago', 'Calera de Tango', true, 123, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13404', 'paine', 'Paine', 'Metropolitana de Santiago', 'Paine', true, 124, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13501', 'melipilla', 'Melipilla', 'Metropolitana de Santiago', 'Melipilla', true, 125, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13502', 'alhue', 'Alhué', 'Metropolitana de Santiago', 'Alhué', true, 126, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13503', 'curacavi', 'Curacaví', 'Metropolitana de Santiago', 'Curacaví', true, 127, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13504', 'maria-pinto', 'María Pinto', 'Metropolitana de Santiago', 'María Pinto', true, 128, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13505', 'san-pedro', 'San Pedro', 'Metropolitana de Santiago', 'San Pedro', true, 129, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13601', 'talagante', 'Talagante', 'Metropolitana de Santiago', 'Talagante', true, 130, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13602', 'el-monte', 'El Monte', 'Metropolitana de Santiago', 'El Monte', true, 131, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13603', 'isla-de-maipo', 'Isla de Maipo', 'Metropolitana de Santiago', 'Isla de Maipo', true, 132, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13604', 'padre-hurtado', 'Padre Hurtado', 'Metropolitana de Santiago', 'Padre Hurtado', true, 133, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_13605', 'penaflor', 'Peñaflor', 'Metropolitana de Santiago', 'Peñaflor', true, 134, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06101', 'rancagua', 'Rancagua', 'Libertador General Bernardo O''Higgins', 'Rancagua', true, 135, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06102', 'codegua', 'Codegua', 'Libertador General Bernardo O''Higgins', 'Codegua', true, 136, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06103', 'coinco', 'Coinco', 'Libertador General Bernardo O''Higgins', 'Coinco', true, 137, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06104', 'coltauco', 'Coltauco', 'Libertador General Bernardo O''Higgins', 'Coltauco', true, 138, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06105', 'donihue', 'Doñihue', 'Libertador General Bernardo O''Higgins', 'Doñihue', true, 139, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06106', 'graneros', 'Graneros', 'Libertador General Bernardo O''Higgins', 'Graneros', true, 140, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06107', 'las-cabras', 'Las Cabras', 'Libertador General Bernardo O''Higgins', 'Las Cabras', true, 141, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06108', 'machali', 'Machalí', 'Libertador General Bernardo O''Higgins', 'Machalí', true, 142, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06109', 'malloa', 'Malloa', 'Libertador General Bernardo O''Higgins', 'Malloa', true, 143, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06110', 'mostazal', 'Mostazal', 'Libertador General Bernardo O''Higgins', 'Mostazal', true, 144, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06111', 'olivar', 'Olivar', 'Libertador General Bernardo O''Higgins', 'Olivar', true, 145, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06112', 'peumo', 'Peumo', 'Libertador General Bernardo O''Higgins', 'Peumo', true, 146, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06113', 'pichidegua', 'Pichidegua', 'Libertador General Bernardo O''Higgins', 'Pichidegua', true, 147, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06114', 'quinta-de-tilcoco', 'Quinta de Tilcoco', 'Libertador General Bernardo O''Higgins', 'Quinta de Tilcoco', true, 148, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06115', 'rengo', 'Rengo', 'Libertador General Bernardo O''Higgins', 'Rengo', true, 149, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06116', 'requinoa', 'Requínoa', 'Libertador General Bernardo O''Higgins', 'Requínoa', true, 150, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06117', 'san-vicente', 'San Vicente', 'Libertador General Bernardo O''Higgins', 'San Vicente', true, 151, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06201', 'pichilemu', 'Pichilemu', 'Libertador General Bernardo O''Higgins', 'Pichilemu', true, 152, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06202', 'la-estrella', 'La Estrella', 'Libertador General Bernardo O''Higgins', 'La Estrella', true, 153, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06203', 'litueche', 'Litueche', 'Libertador General Bernardo O''Higgins', 'Litueche', true, 154, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06204', 'marchihue', 'Marchihue', 'Libertador General Bernardo O''Higgins', 'Marchihue', true, 155, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06205', 'navidad', 'Navidad', 'Libertador General Bernardo O''Higgins', 'Navidad', true, 156, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06206', 'paredones', 'Paredones', 'Libertador General Bernardo O''Higgins', 'Paredones', true, 157, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06301', 'san-fernando', 'San Fernando', 'Libertador General Bernardo O''Higgins', 'San Fernando', true, 158, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06302', 'chepica', 'Chépica', 'Libertador General Bernardo O''Higgins', 'Chépica', true, 159, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06303', 'chimbarongo', 'Chimbarongo', 'Libertador General Bernardo O''Higgins', 'Chimbarongo', true, 160, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06304', 'lolol', 'Lolol', 'Libertador General Bernardo O''Higgins', 'Lolol', true, 161, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06305', 'nancagua', 'Nancagua', 'Libertador General Bernardo O''Higgins', 'Nancagua', true, 162, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06306', 'palmilla', 'Palmilla', 'Libertador General Bernardo O''Higgins', 'Palmilla', true, 163, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06307', 'peralillo', 'Peralillo', 'Libertador General Bernardo O''Higgins', 'Peralillo', true, 164, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06308', 'placilla', 'Placilla', 'Libertador General Bernardo O''Higgins', 'Placilla', true, 165, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06309', 'pumanque', 'Pumanque', 'Libertador General Bernardo O''Higgins', 'Pumanque', true, 166, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_06310', 'santa-cruz', 'Santa Cruz', 'Libertador General Bernardo O''Higgins', 'Santa Cruz', true, 167, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07101', 'talca', 'Talca', 'Maule', 'Talca', true, 168, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07102', 'constitucion', 'Constitución', 'Maule', 'Constitución', true, 169, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07103', 'curepto', 'Curepto', 'Maule', 'Curepto', true, 170, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07104', 'empedrado', 'Empedrado', 'Maule', 'Empedrado', true, 171, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07105', 'maule', 'Maule', 'Maule', 'Maule', true, 172, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07106', 'pelarco', 'Pelarco', 'Maule', 'Pelarco', true, 173, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07107', 'pencahue', 'Pencahue', 'Maule', 'Pencahue', true, 174, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07108', 'rio-claro', 'Río Claro', 'Maule', 'Río Claro', true, 175, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07109', 'san-clemente', 'San Clemente', 'Maule', 'San Clemente', true, 176, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07110', 'san-rafael', 'San Rafael', 'Maule', 'San Rafael', true, 177, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07201', 'cauquenes', 'Cauquenes', 'Maule', 'Cauquenes', true, 178, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07202', 'chanco', 'Chanco', 'Maule', 'Chanco', true, 179, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07203', 'pelluhue', 'Pelluhue', 'Maule', 'Pelluhue', true, 180, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07301', 'curico', 'Curicó', 'Maule', 'Curicó', true, 181, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07302', 'hualane', 'Hualañé', 'Maule', 'Hualañé', true, 182, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07303', 'licanten', 'Licantén', 'Maule', 'Licantén', true, 183, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07304', 'molina', 'Molina', 'Maule', 'Molina', true, 184, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07305', 'rauco', 'Rauco', 'Maule', 'Rauco', true, 185, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07306', 'romeral', 'Romeral', 'Maule', 'Romeral', true, 186, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07307', 'sagrada-familia', 'Sagrada Familia', 'Maule', 'Sagrada Familia', true, 187, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07308', 'teno', 'Teno', 'Maule', 'Teno', true, 188, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07309', 'vichuquen', 'Vichuquén', 'Maule', 'Vichuquén', true, 189, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07401', 'linares', 'Linares', 'Maule', 'Linares', true, 190, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07402', 'colbun', 'Colbún', 'Maule', 'Colbún', true, 191, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07403', 'longavi', 'Longaví', 'Maule', 'Longaví', true, 192, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07404', 'parral', 'Parral', 'Maule', 'Parral', true, 193, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07405', 'retiro', 'Retiro', 'Maule', 'Retiro', true, 194, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07406', 'san-javier', 'San Javier', 'Maule', 'San Javier', true, 195, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07407', 'villa-alegre', 'Villa Alegre', 'Maule', 'Villa Alegre', true, 196, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_07408', 'yerbas-buenas', 'Yerbas Buenas', 'Maule', 'Yerbas Buenas', true, 197, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16101', 'chillan', 'Chillán', 'Ñuble', 'Chillán', true, 198, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16102', 'bulnes', 'Bulnes', 'Ñuble', 'Bulnes', true, 199, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16103', 'chillan-viejo', 'Chillán Viejo', 'Ñuble', 'Chillán Viejo', true, 200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16104', 'el-carmen', 'El Carmen', 'Ñuble', 'El Carmen', true, 201, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16105', 'pemuco', 'Pemuco', 'Ñuble', 'Pemuco', true, 202, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16106', 'pinto', 'Pinto', 'Ñuble', 'Pinto', true, 203, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16107', 'quillon', 'Quillón', 'Ñuble', 'Quillón', true, 204, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16108', 'san-ignacio', 'San Ignacio', 'Ñuble', 'San Ignacio', true, 205, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16109', 'yungay', 'Yungay', 'Ñuble', 'Yungay', true, 206, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16201', 'quirihue', 'Quirihue', 'Ñuble', 'Quirihue', true, 207, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16202', 'cobquecura', 'Cobquecura', 'Ñuble', 'Cobquecura', true, 208, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16203', 'coelemu', 'Coelemu', 'Ñuble', 'Coelemu', true, 209, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16204', 'ninhue', 'Ninhue', 'Ñuble', 'Ninhue', true, 210, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16205', 'portezuelo', 'Portezuelo', 'Ñuble', 'Portezuelo', true, 211, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16206', 'ranquil', 'Ránquil', 'Ñuble', 'Ránquil', true, 212, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16207', 'treguaco', 'Treguaco', 'Ñuble', 'Treguaco', true, 213, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16301', 'san-carlos', 'San Carlos', 'Ñuble', 'San Carlos', true, 214, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16302', 'coihueco', 'Coihueco', 'Ñuble', 'Coihueco', true, 215, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16303', 'niquen', 'Ñiquén', 'Ñuble', 'Ñiquén', true, 216, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16304', 'san-fabian', 'San Fabián', 'Ñuble', 'San Fabián', true, 217, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_16305', 'san-nicolas', 'San Nicolás', 'Ñuble', 'San Nicolás', true, 218, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08101', 'concepcion', 'Concepción', 'Biobío', 'Concepción', true, 219, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08102', 'coronel', 'Coronel', 'Biobío', 'Coronel', true, 220, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08103', 'chiguayante', 'Chiguayante', 'Biobío', 'Chiguayante', true, 221, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08104', 'florida', 'Florida', 'Biobío', 'Florida', true, 222, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08105', 'hualqui', 'Hualqui', 'Biobío', 'Hualqui', true, 223, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08106', 'lota', 'Lota', 'Biobío', 'Lota', true, 224, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08107', 'penco', 'Penco', 'Biobío', 'Penco', true, 225, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08108', 'san-pedro-de-la-paz', 'San Pedro de la Paz', 'Biobío', 'San Pedro de la Paz', true, 226, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08109', 'santa-juana', 'Santa Juana', 'Biobío', 'Santa Juana', true, 227, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08110', 'talcahuano', 'Talcahuano', 'Biobío', 'Talcahuano', true, 228, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08111', 'tome', 'Tomé', 'Biobío', 'Tomé', true, 229, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08112', 'hualpen', 'Hualpén', 'Biobío', 'Hualpén', true, 230, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08201', 'lebu', 'Lebu', 'Biobío', 'Lebu', true, 231, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08202', 'arauco', 'Arauco', 'Biobío', 'Arauco', true, 232, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08203', 'canete', 'Cañete', 'Biobío', 'Cañete', true, 233, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08204', 'contulmo', 'Contulmo', 'Biobío', 'Contulmo', true, 234, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08205', 'curanilahue', 'Curanilahue', 'Biobío', 'Curanilahue', true, 235, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08206', 'los-alamos', 'Los Álamos', 'Biobío', 'Los Álamos', true, 236, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08207', 'tirua', 'Tirúa', 'Biobío', 'Tirúa', true, 237, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08301', 'los-angeles', 'Los Ángeles', 'Biobío', 'Los Ángeles', true, 238, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08302', 'antuco', 'Antuco', 'Biobío', 'Antuco', true, 239, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08303', 'cabrero', 'Cabrero', 'Biobío', 'Cabrero', true, 240, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08304', 'laja', 'Laja', 'Biobío', 'Laja', true, 241, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08305', 'mulchen', 'Mulchén', 'Biobío', 'Mulchén', true, 242, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08306', 'nacimiento', 'Nacimiento', 'Biobío', 'Nacimiento', true, 243, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08307', 'negrete', 'Negrete', 'Biobío', 'Negrete', true, 244, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08308', 'quilaco', 'Quilaco', 'Biobío', 'Quilaco', true, 245, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08309', 'quilleco', 'Quilleco', 'Biobío', 'Quilleco', true, 246, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08310', 'san-rosendo', 'San Rosendo', 'Biobío', 'San Rosendo', true, 247, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08311', 'santa-barbara', 'Santa Bárbara', 'Biobío', 'Santa Bárbara', true, 248, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08312', 'tucapel', 'Tucapel', 'Biobío', 'Tucapel', true, 249, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08313', 'yumbel', 'Yumbel', 'Biobío', 'Yumbel', true, 250, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_08314', 'alto-biobio', 'Alto Biobío', 'Biobío', 'Alto Biobío', true, 251, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09101', 'temuco', 'Temuco', 'La Araucanía', 'Temuco', true, 252, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09102', 'carahue', 'Carahue', 'La Araucanía', 'Carahue', true, 253, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09103', 'cunco', 'Cunco', 'La Araucanía', 'Cunco', true, 254, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09104', 'curarrehue', 'Curarrehue', 'La Araucanía', 'Curarrehue', true, 255, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09105', 'freire', 'Freire', 'La Araucanía', 'Freire', true, 256, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09106', 'galvarino', 'Galvarino', 'La Araucanía', 'Galvarino', true, 257, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09107', 'gorbea', 'Gorbea', 'La Araucanía', 'Gorbea', true, 258, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09108', 'lautaro', 'Lautaro', 'La Araucanía', 'Lautaro', true, 259, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09109', 'loncoche', 'Loncoche', 'La Araucanía', 'Loncoche', true, 260, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09110', 'melipeuco', 'Melipeuco', 'La Araucanía', 'Melipeuco', true, 261, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09111', 'nueva-imperial', 'Nueva Imperial', 'La Araucanía', 'Nueva Imperial', true, 262, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09112', 'padre-las-casas', 'Padre Las Casas', 'La Araucanía', 'Padre Las Casas', true, 263, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09113', 'perquenco', 'Perquenco', 'La Araucanía', 'Perquenco', true, 264, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09114', 'pitrufquen', 'Pitrufquén', 'La Araucanía', 'Pitrufquén', true, 265, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09115', 'pucon', 'Pucón', 'La Araucanía', 'Pucón', true, 266, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09116', 'saavedra', 'Saavedra', 'La Araucanía', 'Saavedra', true, 267, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09117', 'teodoro-schmidt', 'Teodoro Schmidt', 'La Araucanía', 'Teodoro Schmidt', true, 268, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09118', 'tolten', 'Toltén', 'La Araucanía', 'Toltén', true, 269, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09119', 'vilcun', 'Vilcún', 'La Araucanía', 'Vilcún', true, 270, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09120', 'villarrica', 'Villarrica', 'La Araucanía', 'Villarrica', true, 271, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09121', 'cholchol', 'Cholchol', 'La Araucanía', 'Cholchol', true, 272, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09201', 'angol', 'Angol', 'La Araucanía', 'Angol', true, 273, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09202', 'collipulli', 'Collipulli', 'La Araucanía', 'Collipulli', true, 274, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09203', 'curacautin', 'Curacautín', 'La Araucanía', 'Curacautín', true, 275, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09204', 'ercilla', 'Ercilla', 'La Araucanía', 'Ercilla', true, 276, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09205', 'lonquimay', 'Lonquimay', 'La Araucanía', 'Lonquimay', true, 277, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09206', 'los-sauces', 'Los Sauces', 'La Araucanía', 'Los Sauces', true, 278, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09207', 'lumaco', 'Lumaco', 'La Araucanía', 'Lumaco', true, 279, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09208', 'puren', 'Purén', 'La Araucanía', 'Purén', true, 280, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09209', 'renaico', 'Renaico', 'La Araucanía', 'Renaico', true, 281, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09210', 'traiguen', 'Traiguén', 'La Araucanía', 'Traiguén', true, 282, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_09211', 'victoria', 'Victoria', 'La Araucanía', 'Victoria', true, 283, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_14101', 'valdivia', 'Valdivia', 'Los Ríos', 'Valdivia', true, 284, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_14102', 'corral', 'Corral', 'Los Ríos', 'Corral', true, 285, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_14103', 'lanco', 'Lanco', 'Los Ríos', 'Lanco', true, 286, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_14104', 'los-lagos', 'Los Lagos', 'Los Ríos', 'Los Lagos', true, 287, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_14105', 'mafil', 'Máfil', 'Los Ríos', 'Máfil', true, 288, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_14106', 'mariquina', 'Mariquina', 'Los Ríos', 'Mariquina', true, 289, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_14107', 'paillaco', 'Paillaco', 'Los Ríos', 'Paillaco', true, 290, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_14108', 'panguipulli', 'Panguipulli', 'Los Ríos', 'Panguipulli', true, 291, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_14201', 'la-union', 'La Unión', 'Los Ríos', 'La Unión', true, 292, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_14202', 'futrono', 'Futrono', 'Los Ríos', 'Futrono', true, 293, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_14203', 'lago-ranco', 'Lago Ranco', 'Los Ríos', 'Lago Ranco', true, 294, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_14204', 'rio-bueno', 'Río Bueno', 'Los Ríos', 'Río Bueno', true, 295, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10101', 'puerto-montt', 'Puerto Montt', 'Los Lagos', 'Puerto Montt', true, 296, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10102', 'calbuco', 'Calbuco', 'Los Lagos', 'Calbuco', true, 297, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10103', 'cochamo', 'Cochamó', 'Los Lagos', 'Cochamó', true, 298, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10104', 'fresia', 'Fresia', 'Los Lagos', 'Fresia', true, 299, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10105', 'frutillar', 'Frutillar', 'Los Lagos', 'Frutillar', true, 300, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10106', 'los-muermos', 'Los Muermos', 'Los Lagos', 'Los Muermos', true, 301, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10107', 'llanquihue', 'Llanquihue', 'Los Lagos', 'Llanquihue', true, 302, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10108', 'maullin', 'Maullín', 'Los Lagos', 'Maullín', true, 303, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10109', 'puerto-varas', 'Puerto Varas', 'Los Lagos', 'Puerto Varas', true, 304, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10201', 'castro', 'Castro', 'Los Lagos', 'Castro', true, 305, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10202', 'ancud', 'Ancud', 'Los Lagos', 'Ancud', true, 306, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10203', 'chonchi', 'Chonchi', 'Los Lagos', 'Chonchi', true, 307, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10204', 'curaco-de-velez', 'Curaco de Vélez', 'Los Lagos', 'Curaco de Vélez', true, 308, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10205', 'dalcahue', 'Dalcahue', 'Los Lagos', 'Dalcahue', true, 309, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10206', 'puqueldon', 'Puqueldón', 'Los Lagos', 'Puqueldón', true, 310, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10207', 'queilen', 'Queilén', 'Los Lagos', 'Queilén', true, 311, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10208', 'quellon', 'Quellón', 'Los Lagos', 'Quellón', true, 312, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10209', 'quemchi', 'Quemchi', 'Los Lagos', 'Quemchi', true, 313, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10210', 'quinchao', 'Quinchao', 'Los Lagos', 'Quinchao', true, 314, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10301', 'osorno', 'Osorno', 'Los Lagos', 'Osorno', true, 315, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10302', 'puerto-octay', 'Puerto Octay', 'Los Lagos', 'Puerto Octay', true, 316, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10303', 'purranque', 'Purranque', 'Los Lagos', 'Purranque', true, 317, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10304', 'puyehue', 'Puyehue', 'Los Lagos', 'Puyehue', true, 318, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10305', 'rio-negro', 'Río Negro', 'Los Lagos', 'Río Negro', true, 319, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10306', 'san-juan-de-la-costa', 'San Juan de la Costa', 'Los Lagos', 'San Juan de la Costa', true, 320, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10307', 'san-pablo', 'San Pablo', 'Los Lagos', 'San Pablo', true, 321, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10401', 'chaiten', 'Chaitén', 'Los Lagos', 'Chaitén', true, 322, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10402', 'futaleufu', 'Futaleufú', 'Los Lagos', 'Futaleufú', true, 323, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10403', 'hualaihue', 'Hualaihué', 'Los Lagos', 'Hualaihué', true, 324, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_10404', 'palena', 'Palena', 'Los Lagos', 'Palena', true, 325, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_11101', 'coyhaique', 'Coyhaique', 'Aysén del General Carlos Ibáñez del Campo', 'Coyhaique', true, 326, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_11102', 'lago-verde', 'Lago Verde', 'Aysén del General Carlos Ibáñez del Campo', 'Lago Verde', true, 327, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_11201', 'aysen', 'Aysén', 'Aysén del General Carlos Ibáñez del Campo', 'Aysén', true, 328, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_11202', 'cisnes', 'Cisnes', 'Aysén del General Carlos Ibáñez del Campo', 'Cisnes', true, 329, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_11203', 'guaitecas', 'Guaitecas', 'Aysén del General Carlos Ibáñez del Campo', 'Guaitecas', true, 330, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_11301', 'cochrane', 'Cochrane', 'Aysén del General Carlos Ibáñez del Campo', 'Cochrane', true, 331, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_11302', 'o-higgins', 'O''Higgins', 'Aysén del General Carlos Ibáñez del Campo', 'O''Higgins', true, 332, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_11303', 'tortel', 'Tortel', 'Aysén del General Carlos Ibáñez del Campo', 'Tortel', true, 333, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_11401', 'chile-chico', 'Chile Chico', 'Aysén del General Carlos Ibáñez del Campo', 'Chile Chico', true, 334, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_11402', 'rio-ibanez', 'Río Ibáñez', 'Aysén del General Carlos Ibáñez del Campo', 'Río Ibáñez', true, 335, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_12101', 'punta-arenas', 'Punta Arenas', 'Magallanes y de la Antártica Chilena', 'Punta Arenas', true, 336, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_12102', 'laguna-blanca', 'Laguna Blanca', 'Magallanes y de la Antártica Chilena', 'Laguna Blanca', true, 337, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_12103', 'rio-verde', 'Río Verde', 'Magallanes y de la Antártica Chilena', 'Río Verde', true, 338, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_12104', 'san-gregorio', 'San Gregorio', 'Magallanes y de la Antártica Chilena', 'San Gregorio', true, 339, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_12201', 'cabo-de-hornos', 'Cabo de Hornos', 'Magallanes y de la Antártica Chilena', 'Cabo de Hornos', true, 340, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_12202', 'antartica', 'Antártica', 'Magallanes y de la Antártica Chilena', 'Antártica', true, 341, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_12301', 'porvenir', 'Porvenir', 'Magallanes y de la Antártica Chilena', 'Porvenir', true, 342, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_12302', 'primavera', 'Primavera', 'Magallanes y de la Antártica Chilena', 'Primavera', true, 343, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_12303', 'timaukel', 'Timaukel', 'Magallanes y de la Antártica Chilena', 'Timaukel', true, 344, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_12401', 'natales', 'Natales', 'Magallanes y de la Antártica Chilena', 'Natales', true, 345, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mloc_cl_12402', 'torres-del-paine', 'Torres del Paine', 'Magallanes y de la Antártica Chilena', 'Torres del Paine', true, 346, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "regionName" = EXCLUDED."regionName",
  "communeName" = EXCLUDED."communeName",
  "isActive" = true,
  "position" = EXCLUDED."position",
  "updatedAt" = CURRENT_TIMESTAMP;
